# 对主题挖掘的结果进行进一步细分

In [6]:
import time
import pandas as pd

In [7]:
result = pd.read_csv('LDA_clustered_5.csv', encoding='gb18030')
result.head()

id   statdate                                               text  \
0  3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...   
1  3586  2017/8/22                                               转发微博   
2  3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...   
3  3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...   
4  3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...   

       所属分类  
0  气象灾害应急响应  
1      热带风暴  
2      热带风暴  
3      热带风暴  
4      热带风暴

In [8]:
result.set_index('id', inplace=True)
result.head()

statdate                                               text      所属分类
id                                                                          
3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...  气象灾害应急响应
3586  2017/8/22                                               转发微博      热带风暴
3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...      热带风暴
3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...      热带风暴
3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...      热带风暴

## 气象灾害应急响应主题细分

In [9]:
cxtx = result.loc[result.所属分类 == '气象灾害应急响应', :]
cxtx

statdate                                               text      所属分类
id                                                                          
3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...  气象灾害应急响应
3658  2017/8/23  http://t.cn/h91BSI【解除气象灾害应急响应通知】解除气象灾害应急响应通知：目...  气象灾害应急响应
3589  2017/8/22  #天气要闻# 受台风“天鸽”影响，截止到22日20时26分，广州市南沙、番禺、天河、越秀、荔...  气象灾害应急响应
3608  2017/8/23  #天气话你知# #13号台风天鸽# 台风靠近，注意远离海边，山区，洼地等危险区域[doge]...  气象灾害应急响应
3612  2017/8/23  升级气象灾害应急响应通知：市气象灾害应急指挥部决定从23日09时00分起将广州市气象灾害（台...  气象灾害应急响应
3623  2017/8/23  http://t.cn/h91BSI【广州南站应急提醒信息】广州市应急办、广州市交委、广铁集...  气象灾害应急响应
3625  2017/8/23  #13号台风天鸽#  大家注意啦！受“天鸽”影响，8月23日5时至16时期间广深港高铁、厦深...  气象灾害应急响应
3626  2017/8/23  #13号台风天鸽##警惕倒树、高空坠物#市区最大阵风达7-10级，外出要警惕高空落物、树木、...  气象灾害应急响应
3627  2017/8/23  阳台花盆、衣服和其他小杂物记得收好，另外走过路过高楼、广告牌、临时工棚、大树和小树旁边都要注...  气象灾害应急响应
3572  2017/8/22  http://t.cn/h91BSI【启动气象灾害应急响应通知】据市气象台监测，广州市达到启...  气象灾害应急响应
3575  2017/8/22  http://t.cn/h91BSI【解除气象灾害应急响应通知】据市气象台监测，广州市达到解...  气象灾害应急响应
3583  2017/8/22  http://t.cn/h91BSI【解除气象灾害应急响应通知】目前天河区、越秀区、荔湾区、...  气象灾害应急响应
3740  2017/8/26  #14号台风帕卡#记得提前收起阳台的花盆等小杂物，风大雨大期间尽量不外出，因为不知道大风下一...  气象灾害应急响应
3741  2017/8/26  http://t.cn/h91BSI【启动气象灾害应急响应通知】据市气象台监测，广州市达到启...  气象灾害应急响应
3634  2017/8/23  【广州市三防办水情信息】受天鸽台风风暴潮增水影响，预计中站和黄埔站将出现超100年一遇的高潮...  气象灾害应急响应
3761  2017/8/26  http://t.cn/h91BSI【台风“帕卡”预警信息】广州市政府应急办、三防办、气象局...  气象灾害应急响应
3773  2017/8/26  省政府应急办、省三防办、省气象局提醒您：台风影响期间，社会公众务必服从当地政府的防灾部署，避...  气象灾害应急响应
3776  2017/8/26  #天气话你知# 台风“帕卡”跑这么快，急着去追“天鸽”了。小姐姐告诉您[小黄人高兴]：明后天...  气象灾害应急响应
3883  2017/8/28  http://t.cn/h91BSI【解除气象灾害应急响应通知】据市气象台监测，广州市达到解...  气象灾害应急响应
3886  2017/8/28                      #小编8科普# 连续降雨过后，要注意防御地质灾害哦[来]~  气象灾害应急响应
3896  2017/8/28  【广州地质灾害气象风险预警】广州市国土资源和规划委员会、气象局提醒你：预计未来24小时，广州...  气象灾害应急响应
3787  2017/8/26  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...  气象灾害应急响应
3794  2017/8/26  #帕卡影响广州#预计自27日凌晨开始，受台风“帕卡”影响，风开始加大，27日白天风雨逐渐加大...  气象灾害应急响应
3797  2017/8/27  http://t.cn/h91BSI【警惕大风和暴雨】受台风“帕卡”影响，预计广州清晨风力开...  气象灾害应急响应
3806  2017/8/27  #帕卡影响广州#来自南站默默等车的小伙伴。预计今天上午风雨就开始对飞机、高铁、轻轨、水上交通...  气象灾害应急响应
3808  2017/8/27  #14号台风帕卡##帕卡影响广州# 截至8月27日7时40分，广州中南部台风橙色预警、暴雨黄...  气象灾害应急响应
3813  2017/8/27  【早安，广州】#14号台风帕卡# #帕卡影响广州# 14号台风“帕卡”在今日08时加强为台风...  气象灾害应急响应
3826  2017/8/27                             #14号台风帕卡# 出门一定要注意安全！！！  气象灾害应急响应
3832  2017/8/27  http://t.cn/h91BSI【降级气象灾害应急响应通知】据市气象台监测，广州市达到降...  气象灾害应急响应
3837  2017/8/27  #14号台风帕卡##帕卡影响广州# “帕卡”渐行渐远，目前全市各区的台风蓝色预警信号，除从化...  气象灾害应急响应
...         ...                                                ...       ...
8282  2018/3/19  【启动气象灾害应急响应通知】据市气象台监测，目前广州市达到启动气象灾害（强对流）Ⅲ级应急响应...  气象灾害应急响应
7878   2018/3/3  发布了头条文章：《广州春运天气20180303》 #广州春运天气# 预计，4日开始受弱切变线...  气象灾害应急响应
8424  2018/4/22  【拜祭提醒】广州市应急办、民政局提醒您：预计今天特别是9时至11时、14时至16时我市各主要...  气象灾害应急响应
8430  2018/4/22  【拜祭提醒】广州市应急办、民政局提醒您：预计今日特别是14时至16时，我市各主要拜祭场所将出...  气象灾害应急响应
8432  2018/4/22  【拜祭提醒】广州市应急办、民政局提醒您：预计今日特别是14时至16时，我市各主要拜祭场所将出...  气象灾害应急响应
8434  2018/4/22  #每日一图#昨日谜底：蜜蜂采花忙，短期有雨降.泥萌都猜到了吗？今日这个是来自二年级叶皓丹小朋...  气象灾害应急响应
8437  2018/4/22  #天气要闻# 大到暴雨向您发出好友申请：《前方高能：大到暴雨约定你~》  http://t....  气象灾害应急响应
7353   2018/2/9  #广州春运天气#就是这个“广州春运气象服务知多D【live】”，等会首席出镜。 http:/...  气象灾害应急响应
2165  2017/6/24  #小编8天气# 愿平安，大家出游要留意天气变化，因为强降水也可能会引发山体滑坡、泥石流//@...  气象灾害应急响应
8313  2018/3/20                               花花好坚强，挨过了昨天的风吹雨打[憧憬]  气象灾害应急响应
7908   2018/3/4    [doge]正想编一条类似的，结果就看到小深深发出来这个，嗯，差不多就是这个意思，下午没啥雨。  气象灾害应急响应
7922   2018/3/5                                   [吃惊][吃惊]福州这一波好强啊  气象灾害应急响应
2869  2017/7/24  #随手拍广州# 大家有什么珠江新、老照片可以发来给小编吗？？[小黄人高兴] 发布了头条文章：...  气象灾害应急响应
7615  2018/2/20               #随手拍广州# 夕阳，你好[赞] http://t.cn/R2WJCGP  气象灾害应急响应
2194  2017/6/25                   #随手拍广州# 你站在桥上看风景，看风景的人在楼上看你[可爱]～  气象灾害应急响应
6869  2018/1/21  //@央视新闻:【乌鲁木齐城区大范围震感明显】地震发生时，乌鲁木齐城区大范围及周边昌吉市、五...  气象灾害应急响应
2899  2017/7/25  【水调歌头·游泳】#横渡珠江#才饮长沙水，又食武昌鱼。万里长江横渡，极目楚天舒。不管风吹浪打...  气象灾害应急响应
2902  2017/7/25                 #横渡珠江# 为了降低下水前后的温差，工作人员持续给各位渡江人员淋水  气象灾害应急响应
2906  2017/7/25  #横渡珠江一线报道#新快报记者对现场气象保障充满好奇呢[憧憬]。邹冠武处长向记者介绍，广州市...  气象灾害应急响应
685

In [10]:
X = cxtx.loc[:, ['text']]

In [11]:
X.shape

(282, 1)

In [12]:
X.head()

text
id                                                     
3585  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...
3658  http://t.cn/h91BSI【解除气象灾害应急响应通知】解除气象灾害应急响应通知：目...
3589  #天气要闻# 受台风“天鸽”影响，截止到22日20时26分，广州市南沙、番禺、天河、越秀、荔...
3608  #天气话你知# #13号台风天鸽# 台风靠近，注意远离海边，山区，洼地等危险区域[doge]...
3612  升级气象灾害应急响应通知：市气象灾害应急指挥部决定从23日09时00分起将广州市气象灾害（台...

In [13]:
X.dtypes

text    object
dtype: object

In [14]:
X.text.describe()

count                                                   282
unique                                                  272
top       【拜祭提醒】广州市应急办、民政局提醒您：预计今日特别是14时至16时，我市各主要拜祭场所将出...
freq                                                      4
Name: text, dtype: object

In [15]:
import jieba

In [16]:
def chinese_word_cut(mytext):
    return ' '.join(jieba.cut(mytext))

In [17]:
jieba.load_userdict("userdict_weibo.txt")

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\1\jieba.cache
Loading model cost 1.756 seconds.
Prefix dict has been built succesfully.


In [18]:
%%time
X['cutted_text'] = X.text.apply(chinese_word_cut)

Wall time: 422 ms


In [19]:
X.head()

text  \
id                                                        
3585  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...   
3658  http://t.cn/h91BSI【解除气象灾害应急响应通知】解除气象灾害应急响应通知：目...   
3589  #天气要闻# 受台风“天鸽”影响，截止到22日20时26分，广州市南沙、番禺、天河、越秀、荔...   
3608  #天气话你知# #13号台风天鸽# 台风靠近，注意远离海边，山区，洼地等危险区域[doge]...   
3612  升级气象灾害应急响应通知：市气象灾害应急指挥部决定从23日09时00分起将广州市气象灾害（台...   

                                            cutted_text  
id                                                       
3585  http : / / t . cn / h91BSI 【 升级 气象 灾害 应急 响应 通知...  
3658  http : / / t . cn / h91BSI 【 解除 气象 灾害 应急 响应 通知...  
3589  # 天气要闻 #   受 台风 “ 天鸽 ” 影响 ， 截止 到 22 日 20 时 26 ...  
3608  # 天气话你知 #   # 13号台风天鸽 #   台风 靠近 ， 注意 远离 海边 ， 山...  
3612  升级 气象 灾害 应急 响应 通知 ： 市 气象 灾害 应急 指挥部 决定 从 23 日 0...

In [20]:
X.shape

(282, 2)

In [21]:
def get_custom_stopwords(stop_words_file):
    with open(stop_words_file, encoding='utf-8') as f:
        stopwords = f.read( )
    stopwords_list = stopwords.split('\n')
    custom_stopwords_list = [i for i in stopwords_list]
    return custom_stopwords_list

In [22]:
stop_words_file = 'mystopwords.txt'
stopwords = get_custom_stopwords(stop_words_file)

In [23]:
stopwords[-10:]

['划重点', '没错', '缓慢', '增加', '务必', '较强', '辐射', '时段', '雷雨', '']

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
vect = CountVectorizer()

In [26]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [27]:
term_matrix.head()

00  01  03  05  07  08  09  10  100  1016 ...   黄村  黄梓洋  黄绿色  黄色  黄色预警信号  \
0   0   0   0   0   0   0   0   0    0     0 ...    0    0    0   0       0   
1   0   0   0   0   0   0   0   0    0     0 ...    0    0    0   0       0   
2   0   0   0   0   0   0   0   0    0     0 ...    0    0    0   0       1   
3   0   0   0   0   0   0   0   0    0     0 ...    0    0    0   0       0   
4   2   0   0   0   0   0   2   0    0     0 ...    0    0    0   0       0   

   默默  鼓掌  龙江  龙洞  龟蛇静  
0   0   0   0   0    0  
1   0   0   0   0    0  
2   0   0   0   0    0  
3   0   0   0   0    0  
4   0   0   0   0    0  

[5 rows x 1793 columns]

In [28]:
term_matrix.shape

(282, 1793)

In [29]:
vect = CountVectorizer(stop_words=frozenset(stopwords)) #加上停用词去除功能

In [30]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [31]:
term_matrix.head()

00  01  03  05  07  08  09  10  100  1016 ...   黄村  黄梓洋  黄绿色  黄色  黄色预警信号  \
0   0   0   0   0   0   0   0   0    0     0 ...    0    0    0   0       0   
1   0   0   0   0   0   0   0   0    0     0 ...    0    0    0   0       0   
2   0   0   0   0   0   0   0   0    0     0 ...    0    0    0   0       1   
3   0   0   0   0   0   0   0   0    0     0 ...    0    0    0   0       0   
4   2   0   0   0   0   0   2   0    0     0 ...    0    0    0   0       0   

   默默  鼓掌  龙江  龙洞  龟蛇静  
0   0   0   0   0    0  
1   0   0   0   0    0  
2   0   0   0   0    0  
3   0   0   0   0    0  
4   0   0   0   0    0  

[5 rows x 1483 columns]

In [32]:
max_df = 0.8 # 在超过这一比例的文档中出现的关键词（过于平凡），去除掉。
min_df = 3 # 在地狱这一数量的文档中出现的关键词（过于独特），去除掉。

In [33]:
vect = CountVectorizer(max_df=max_df,
                      min_df=min_df,
                      token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                      stop_words=frozenset(stopwords))

In [34]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [35]:
term_matrix.head()

doge  iii  ps  一条  上学  上班  不语  专人  专家  世界   ...    高温  高空  高铁  鲜花  黄人  黄埔区  \
0     0    0   0   0   0   0   0   0   0   0   ...     0   0   0   0   0    0   
1     0    0   0   0   0   0   0   0   0   0   ...     0   0   0   0   0    0   
2     0    0   0   0   0   1   0   0   0   0   ...     0   0   0   0   0    0   
3     1    0   0   0   0   0   0   0   0   0   ...     0   0   0   0   0    0   
4     0    0   0   0   0   0   0   0   0   0   ...     0   0   0   0   0    0   

   黄村  黄绿色  黄色  黄色预警信号  
0   0    0   0       0  
1   0    0   0       0  
2   0    0   0       1  
3   0    0   0       0  
4   0    0   0       0  

[5 rows x 263 columns]

In [36]:
n_features = 1000

In [37]:
tf_vectorizer = CountVectorizer(max_features=n_features,
                               max_df=max_df,
                               min_df=min_df,
                               token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                               stop_words=frozenset(stopwords))

In [38]:
term_matrix = pd.DataFrame(tf_vectorizer.fit_transform(X.cutted_text).toarray(), columns=tf_vectorizer.get_feature_names())

In [39]:
term_matrix.head()

doge  iii  ps  一条  上学  上班  不语  专人  专家  世界   ...    高温  高空  高铁  鲜花  黄人  黄埔区  \
0     0    0   0   0   0   0   0   0   0   0   ...     0   0   0   0   0    0   
1     0    0   0   0   0   0   0   0   0   0   ...     0   0   0   0   0    0   
2     0    0   0   0   0   1   0   0   0   0   ...     0   0   0   0   0    0   
3     1    0   0   0   0   0   0   0   0   0   ...     0   0   0   0   0    0   
4     0    0   0   0   0   0   0   0   0   0   ...     0   0   0   0   0    0   

   黄村  黄绿色  黄色  黄色预警信号  
0   0    0   0       0  
1   0    0   0       0  
2   0    0   0       1  
3   0    0   0       0  
4   0    0   0       0  

[5 rows x 263 columns]

In [40]:
term_matrix.shape

(282, 263)

In [41]:
tf = tf_vectorizer.fit_transform(X.cutted_text)

In [42]:
from sklearn.decomposition import LatentDirichletAllocation

In [43]:
n_topics = 6
lda = LatentDirichletAllocation(n_topics=n_topics,
                               max_iter=50,
                               learning_method='online',
                               learning_offset=50.,
                               random_state=0)

In [44]:
%%time
lda.fit(tf)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


Wall time: 4.16 s


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=50, mean_change_tol=0.001,
             n_components=10, n_jobs=1, n_topics=6, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [45]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print('Topic #%d:' % topic_idx)
        print(' '.join([feature_names[i]
                      for i in topic.argsort()[:-n_top_words -1:-1]]))
    print()

In [46]:
n_top_words = 20

In [47]:
tf_feature_names = tf_vectorizer.get_feature_names()
print_top_words(lda, tf_feature_names, n_top_words)

Topic #0:
预警 横渡珠江 天气话你知 学生 延迟上学 闪电 短时 上班 打雷 留意 大雾 文章 防雷 头条 出门 场所 市区 湿身 措施 上学
Topic #1:
拜祭 场所 每日一图 时至 提醒 公共 小朋友 缅怀 紧张 谚语 周边 鲜花 人流 作品 我市 交通工具 广州市 提醒您 应急 选择
Topic #2:
台风 登高 临时 广告牌 注意安全 暴雨 工棚 杂物 高空 危险 阳台 预警 衣服 路过 外出 重阳 帕卡 落物 防御 天鸽
Topic #3:
黄人 高兴 留意 保障 活动 广州春运天气 预报 地震 小编 现场 信息 服务 广州市 变化 大到暴雨 小编8天气 随手拍广州 气象局 平安 范围
Topic #4:
花市 应急 市民 中心 广大 吃惊 提醒您 预警 风景 广州市 平安 新春愉快 吉祥 恭祝 气象局 doge 天河 随手拍广州 一条 温馨提醒
Topic #5:
气象 应急 灾害 响应 广州市 指挥部 启动 通知 解除 气象台 监测 据市 暴雨 办公室 规定 防御 预案 台风 高温 升级



In [48]:
import pyLDAvis
import pyLDAvis.sklearn
pyLDAvis.enable_notebook()
pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]


PreparedData(topic_coordinates=            Freq  cluster  topics         x         y
topic                                                
5      52.360345        1       1  0.391899  0.082949
2      13.662420        1       2 -0.079551  0.017337
3      11.049542        1       3 -0.113708  0.120092
0      10.071047        1       4 -0.180748  0.121476
1       8.602051        1       5 -0.014245 -0.305432
4       4.254594        1       6 -0.003647 -0.036422, topic_info=     Category        Freq   Term       Total  loglift  logprob
term                                                          
157   Default  367.000000     气象  367.000000  30.0000  30.0000
171   Default  281.000000     灾害  281.000000  29.0000  29.0000
109   Default  319.000000     应急  319.000000  28.0000  28.0000
121   Default   48.000000     拜祭   48.000000  27.0000  27.0000
58    Default  183.000000     响应  183.000000  26.0000  26.0000
105   Default  196.000000    广州市  196.000000  25.0000  25.0000
247   Default   45.000000     预警   45.000000  24.0000  24.0000
124   Default  101.000000    指挥部  101.000000  23.0000  23.0000
56    Default   97.000000     启动   97.000000  22.0000  22.0000
52    Default   45.000000     台风   45.000000  21.0000  21.0000
65    Default   26.000000     场所   26.000000  20.0000  20.0000
195   Default   12.000000     花市   12.000000  19.0000  19.0000
178   Default   27.000000     留意   27.000000  18.0000  18.0000
257   Default   18.000000     黄人   18.000000  17.0000  17.0000
131   Default   20.000000    提醒您   20.000000  16.0000  16.0000
152   Default   19.000000   横渡珠江   19.000000  15.0000  15.0000
251   Default   16.000000     高兴   16.000000  14.0000  14.0000
154   Default   14.000000   每日一图   14.000000  13.0000  13.0000
180   Default   18.000000     登高   18.000000  12.0000  12.0000
143   Default   18.000000     时至   18.000000  11.0000  11.0000
25    Default   15.000000     保障   15.000000  10.0000  10.0000
159   Default   15.000000    气象局   15.000000   9.0000   9.0000
101   Default   13.000000     平安   13.000000   8.0000   8.0000
82    Default   14.000000     学生   14.000000   7.0000   7.0000
110   Default   13.000000   延迟上学   13.000000   6.0000   6.0000
222   Default   65.000000     通知   65.000000   5.0000   5.0000
205   Default   64.000000     解除   64.000000   4.0000   4.0000
73    Default   17.000000  天气话你知   17.000000   3.0000   3.0000
137   Default   19.000000     文章   19.000000   2.0000   2.0000
232   Default   13.000000     闪电   13.000000   1.0000   1.0000
...       ...         ...    ...         ...      ...      ...
114    Topic6    5.787389     恭祝    6.685775   3.0129  -3.4122
11     Topic6    7.178688     中心    9.405653   2.8870  -3.1968
50     Topic6    2.446760     发表    3.339426   2.8461  -4.2731
75     Topic6    4.849894     天河    6.642485   2.8426  -3.5889
3      Topic6    2.937501     一条    4.627855   2.7026  -4.0903
108    Topic6    1.921792     广马    3.441303   2.5746  -4.5146
168    Topic6    2.480459   温馨提醒    4.979740   2.4602  -4.2594
0      Topic6    5.242724   doge   11.452126   2.3758  -3.5111
92     Topic6    2.416037  小编8科普    5.310962   2.3695  -4.2858
101    Topic6    5.789255     平安   13.475236   2.3123  -3.4119
84     Topic6    1.037778     家人    2.527843   2.2669  -5.1308
24     Topic6    1.037708     保证    2.571580   2.2497  -5.1309
149    Topic6    1.037782     来袭    2.748799   2.1831  -5.1308
155    Topic6    1.048993     比较    2.838020   2.1619  -5.1201
159    Topic6    5.604102    气象局   15.985136   2.1090  -3.4444
131    Topic6    6.512646    提醒您   20.986336   1.9870  -3.2941
129    Topic6    2.479870     提示    9.138812   1.8528  -4.2597
240    Topic6    2.950780  随手拍广州   11.245672   1.8193  -4.0858
41     Topic6    1.326029     北京    5.091894   1.8117  -4.8857
122    Topic6    1.048260     拥挤    4.642727   1.6690  -5.1208
225    Topic6    1.047955     避开    4.643238   1.6686  -5.1211
193    Topic6    0.567190     统统    2.655905   1.6133  -5.7350
210    Topic6    1.048438     财产    5.032196   1.5886  -5.12

In [49]:
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)

In [58]:
%%time
n_topics = 3    #此处的10可以自定义
lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0)
lda.fit(tf)
print_top_words(lda, tf_feature_names, n_top_words)
pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


Topic #0:
留意 预警 黄人 文章 高兴 小编8天气 头条 天气话你知 信息 横渡珠江 台风 随手拍广州 变化 上班 学生 广州春运天气 延迟上学 出门 闪电 短时
Topic #1:
拜祭 广州市 应急 提醒您 周边 气象局 活动 花市 场所 时至 保障 提醒 每日一图 人流 预警 doge 登高 公共 中心 现场
Topic #2:
气象 应急 灾害 响应 广州市 指挥部 启动 通知 解除 气象台 监测 暴雨 据市 办公室 防御 规定 预案 台风 高温 升级



D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]


Wall time: 13.1 s


In [59]:
%%time
data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
pyLDAvis.show(data)

D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]



Note: if you're in the IPython notebook, pyLDAvis.show() is not the best command
      to use. Consider using pyLDAvis.display(), or pyLDAvis.enable_notebook().
      See more information at http://pyLDAvis.github.io/quickstart.html .

You must interrupt the kernel to end this command

Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]


127.0.0.1 - - [21/Jul/2018 22:22:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Jul/2018 22:23:00] "GET /LDAvis.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jul/2018 22:23:00] "GET /d3.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Jul/2018 22:23:00] "GET /LDAvis.js HTTP/1.1" 200 -



stopping Server...
Wall time: 1min 19s


## 气象灾害应急响应细分主题的结果打标签

In [60]:
# Doc Topics 结果
# 通过fit_transform函数,可以得到文档主题分布,Doc_Topic distribution matrix
doctopic_matrix = lda.fit_transform(tf) # numpy.ndarray
print(doctopic_matrix)
print(doctopic_matrix.shape)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


[[ 0.00998317  0.00994932  0.9800675 ]
 [ 0.01031601  0.0098463   0.97983769]
 [ 0.82328215  0.06157497  0.11514288]
 [ 0.577385    0.38886165  0.03375335]
 [ 0.01163029  0.01163301  0.9767367 ]
 [ 0.21248198  0.53606941  0.25144861]
 [ 0.63652256  0.29673452  0.06674292]
 [ 0.24137955  0.73080749  0.02781296]
 [ 0.58436613  0.39600189  0.01963198]
 [ 0.01044784  0.01050365  0.97904851]
 [ 0.00981442  0.00988892  0.98029665]
 [ 0.11669002  0.01162863  0.87168134]
 [ 0.90354993  0.04879426  0.04765581]
 [ 0.00941877  0.00952608  0.98105515]
 [ 0.52948315  0.23864481  0.23187205]
 [ 0.43298361  0.54199887  0.02501752]
 [ 0.01414805  0.97436285  0.01148909]
 [ 0.78391315  0.19511143  0.02097543]
 [ 0.00983237  0.00989572  0.98027191]
 [ 0.80874041  0.09331413  0.09794546]
 [ 0.02579888  0.83030426  0.14389687]
 [ 0.00948733  0.00940202  0.98111065]
 [ 0.95656154  0.02235724  0.02108122]
 [ 0.44749546  0.53713382  0.01537072]
 [ 0.62976757  0.32851331  0.04171913]
 [ 0.42556288  0.56451129

In [61]:
doctopic = pd.DataFrame(doctopic_matrix, columns=['气象灾害应急响应：延迟上学',
                                                  '气象灾害应急响应：拜祭提醒',
                                                  '气象灾害应急响应：灾害响应',])
#注意此处的主题排序是根据print_top_words(lda, tf_feature_names, n_top_words)的关键词来确定的，而非ldavis呈现的12345，那里只是按照热度排序。
doctopic.head()

气象灾害应急响应：延迟上学  气象灾害应急响应：拜祭提醒  气象灾害应急响应：灾害响应
0       0.009983       0.009949       0.980068
1       0.010316       0.009846       0.979838
2       0.823282       0.061575       0.115143
3       0.577385       0.388862       0.033753
4       0.011630       0.011633       0.976737

In [62]:
doctopic.shape

(282, 3)

In [63]:
global collist
collist = list(doctopic.columns)

def appendmax(sr):
    one = sr.idxmax()
    maxindex = pd.Series(one)
    sr = sr.append(maxindex)
    return sr

dfe = doctopic.apply(lambda x:appendmax(x), axis=1)
dfe.columns = collist + ['所属分类']
# dfe.to_csv('cluster.csv')
dfe.head()

气象灾害应急响应：延迟上学  气象灾害应急响应：拜祭提醒  气象灾害应急响应：灾害响应           所属分类
0       0.009983       0.009949       0.980068  气象灾害应急响应：灾害响应
1       0.010316       0.009846       0.979838  气象灾害应急响应：灾害响应
2       0.823282       0.061575       0.115143  气象灾害应急响应：延迟上学
3       0.577385       0.388862       0.033753  气象灾害应急响应：延迟上学
4       0.011630       0.011633       0.976737  气象灾害应急响应：灾害响应

In [64]:
dfe.shape

(282, 4)

In [65]:
cxtx.head()

statdate                                               text      所属分类
id                                                                          
3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...  气象灾害应急响应
3658  2017/8/23  http://t.cn/h91BSI【解除气象灾害应急响应通知】解除气象灾害应急响应通知：目...  气象灾害应急响应
3589  2017/8/22  #天气要闻# 受台风“天鸽”影响，截止到22日20时26分，广州市南沙、番禺、天河、越秀、荔...  气象灾害应急响应
3608  2017/8/23  #天气话你知# #13号台风天鸽# 台风靠近，注意远离海边，山区，洼地等危险区域[doge]...  气象灾害应急响应
3612  2017/8/23  升级气象灾害应急响应通知：市气象灾害应急指挥部决定从23日09时00分起将广州市气象灾害（台...  气象灾害应急响应

In [66]:
cxtx.shape

(282, 3)

In [67]:
cxtx.drop('所属分类', axis=1, inplace=True)
cxtx.shape

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


(282, 2)

In [68]:
cxtx.head()

statdate                                               text
id                                                                
3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...
3658  2017/8/23  http://t.cn/h91BSI【解除气象灾害应急响应通知】解除气象灾害应急响应通知：目...
3589  2017/8/22  #天气要闻# 受台风“天鸽”影响，截止到22日20时26分，广州市南沙、番禺、天河、越秀、荔...
3608  2017/8/23  #天气话你知# #13号台风天鸽# 台风靠近，注意远离海边，山区，洼地等危险区域[doge]...
3612  2017/8/23  升级气象灾害应急响应通知：市气象灾害应急指挥部决定从23日09时00分起将广州市气象灾害（台...

In [69]:
cxtx.to_csv('cxtx.csv', encoding='gb18030')

In [70]:
cxtx = pd.read_csv('cxtx.csv', encoding='gb18030')
cxtx.head()

id   statdate                                               text
0  3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...
1  3658  2017/8/23  http://t.cn/h91BSI【解除气象灾害应急响应通知】解除气象灾害应急响应通知：目...
2  3589  2017/8/22  #天气要闻# 受台风“天鸽”影响，截止到22日20时26分，广州市南沙、番禺、天河、越秀、荔...
3  3608  2017/8/23  #天气话你知# #13号台风天鸽# 台风靠近，注意远离海边，山区，洼地等危险区域[doge]...
4  3612  2017/8/23  升级气象灾害应急响应通知：市气象灾害应急指挥部决定从23日09时00分起将广州市气象灾害（台...

In [71]:
frames = [cxtx, dfe['所属分类']]
result = pd.concat(frames, axis = 1)
result.head()

id   statdate                                               text  \
0  3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...   
1  3658  2017/8/23  http://t.cn/h91BSI【解除气象灾害应急响应通知】解除气象灾害应急响应通知：目...   
2  3589  2017/8/22  #天气要闻# 受台风“天鸽”影响，截止到22日20时26分，广州市南沙、番禺、天河、越秀、荔...   
3  3608  2017/8/23  #天气话你知# #13号台风天鸽# 台风靠近，注意远离海边，山区，洼地等危险区域[doge]...   
4  3612  2017/8/23  升级气象灾害应急响应通知：市气象灾害应急指挥部决定从23日09时00分起将广州市气象灾害（台...   

            所属分类  
0  气象灾害应急响应：灾害响应  
1  气象灾害应急响应：灾害响应  
2  气象灾害应急响应：延迟上学  
3  气象灾害应急响应：延迟上学  
4  气象灾害应急响应：灾害响应

In [72]:
result.to_csv('LDA_clustered_cxtx.csv', encoding='gb18030')

In [73]:
# %%time
# n_topics = 10    #此处的10可以自定义
# lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
#                                 learning_method='online',
#                                 learning_offset=50.,
#                                 random_state=0)
# lda.fit(tf)
# print_top_words(lda, tf_feature_names, n_top_words)
# pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

# %%time
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)