# 对主题挖掘的结果进行进一步细分

In [90]:
import time
import pandas as pd
%matplotlib inline

In [91]:
result = pd.read_csv('LDA_clustered_5.csv', encoding='gb18030')
result.head()

id   statdate                                               text  \
0  3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...   
1  3586  2017/8/22                                               转发微博   
2  3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...   
3  3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...   
4  3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...   

       所属分类  
0  气象灾害应急响应  
1      热带风暴  
2      热带风暴  
3      热带风暴  
4      热带风暴

In [92]:
result.set_index('id', inplace=True)
result.head()

statdate                                               text      所属分类
id                                                                          
3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...  气象灾害应急响应
3586  2017/8/22                                               转发微博      热带风暴
3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...      热带风暴
3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...      热带风暴
3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...      热带风暴

## 日常预报主题细分

In [93]:
rcyb = result.loc[result.所属分类 == '日常天气预报', :]
rcyb

statdate                                               text    所属分类
id                                                                         
3671   2017/8/24  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市有阵雨，并伴...  日常天气预报
3591   2017/8/22                                             大家注意啦！  日常天气预报
3600   2017/8/23  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市受台风“天鸽...  日常天气预报
3605   2017/8/23  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：阴天，有...  日常天气预报
3688   2017/8/24  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市多云...  日常天气预报
3696   2017/8/24  http://t.cn/h91BSI【广州下班天气】据广州市气象台预测：目前我市多云。 预计...  日常天气预报
3557   2017/8/22  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，全市晴到多...  日常天气预报
3874   2017/8/28  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前广州城区、花都、...  日常天气预报
3877   2017/8/28  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：阴天，有...  日常天气预报
3890   2017/8/28  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市各区...  日常天气预报
3897   2017/8/28  http://t.cn/h91BSI【广州下班天气】据广州市气象台预测：目前我市中南部地区有...  日常天气预报
3902   2017/8/29  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市多云。预计今...  日常天气预报
3904   2017/8/29  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：多云；夜...  日常天气预报
3910   2017/8/29  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市各区...  日常天气预报
3915   2017/8/29  http://t.cn/h91BSI【广州下班天气】据广州市气象台预测：目前我市多云到晴。 ...  日常天气预报
3919   2017/8/30  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市多云。预计今...  日常天气预报
3920   2017/8/30  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：晴到多云...  日常天气预报
3704   2017/8/25  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市多云。预计今...  日常天气预报
3705   2017/8/25  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：多云，午...  日常天气预报
3845   2017/8/27                                 //@广州铁路: #广铁出行微提示#  日常天气预报
3713   2017/8/25  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市花都...  日常天气预报
3730   2017/8/25  http://t.cn/h91BSI【广州下班天气】据广州市气象台预测：目前我市增城区、从化...  日常天气预报
3736   2017/8/26  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：多云，有...  日常天气预报
4026   2017/9/10  【广州午间天气预报】据广州市气象台监测：目前，广州市区、黄埔、增城、番禺、白云、花都区有雷阵...  日常天气预报
4105   2017/9/13  【广州下班天气】据广州市气象台预测：目前我市晴间多云。 预计今天傍晚下班高峰期，广州市区晴间...  日常天气预报
4108   2017/9/14  【广州上班天气】据广州市气象台预测：目前我市晴间多云。预计今天上午上班高峰期，广州市区晴到多...  日常天气预报
4109   2017/9/14  【广州市今日天气】据广州市气象台预测：今日白天：晴到多云，局部有雷阵雨；夜间：多云，局部有雷...  日常天气预报
4114   2017/9/14  【广州午间天气预报】据广州市气象台监测：目前，广州市各区晴到多云。预计12-15时，广州市各...  日常天气预报
3753   2017/8/26  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，我市各区多...  日常天气预报
4072   2017/9/12  【广州上班天气】据广州市气象台预测：目前我市多云。预计今天上午上班高峰期，广州市区晴到多云，...  日常天气预报
...          ...                                                ...     ...
7252    2018/2/5  【广州上班天气】#天气话你知#据广州市气象台预测：目前我市多云。预计今天上午上班高峰期，广州...  日常天气预报
7253    2018/2/5  【广州市今日天气】#天气话你知#据广州市气象台预测：今日白天：多云；夜间：晴间多云；气温介于...  日常天气预报
7261    2018/2/5  【广州午间天气预报】#天气话你知#据广州市气象台监测：目前，广州市各区多云。预计12-15时...  日常天气预报
7580   2018/2/19  【广州市今日天气】#天气话你知#据广州市气象台预测：今日白天：阴天间多云；夜间：阴天，有零星...  日常天气预报
7588   2018/2/19  【广州午间天气预报】#天气话你知#据广州市气象台监测：目前，广州市各区多云。预计12-15时...  日常天气预报
5920  2017/12/15  【广州下班天气】#天气话你知#据广州市气象台预测：目前我市阴天间多云。 预计今天傍晚下班高峰...  日常天气预报
5963  2017/12/17  【广州午间天气预报】#天气话你知#据广州市气象台监测：目前，广州市阴天间多云。预计12-15...  日常天气预报
5978  2017/12/18  【广州上班天气】#天气话你知#据广州市气象台预测：目前我市多云。预计今天上午上班高峰期，广州...  日常天气预报
5980  2017/12/18  【广州市今日天气】#天气话你知#据广州市气象台预测：今日白天：晴间多云；夜间：晴间多云；气温...  日常天气预报
2381    2017/7/3  【广州上班天气】#天气话你知#据广州市气象台预测：预计今天上午上班高峰期，广州市区阴天，有雷...  日常天气预报
2387    2017/7/3  【广州市今日天气】据广州市气象台预测：今日白天：阴天间多云，有中雷雨，局部大雨；夜间：阴天到...  日常天气预报
3502   2017/8/21  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市晴。预计今天...  日常天气预报
3503   2017/8/21  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：晴间多云...  日常天气预报
6396    2018/1/5                                    #论如何强行下雪#科技点亮生活  日常天气预报
6402    2018/1/5  【广州下班天气】#天气话你知#据广州市气象台预测：目前我市阴天。 预计今天傍晚下班高峰期，广...  日常天气预报
6405    2018/1/5                              你若安好便是晴天，广州天气与你相伴[爱你]  日常天气预报
6408    2018/1/6  【广州市今日天气】#天气话你知#据广州市气象台预测：今日白天：阴天，有小雨；夜间：阴天，有大...  日常天气预报
6473    2018/1/8  【广州上班天气】#天气话你知#据广州市气象台预测：目前我市阴天，有小雨。预计今天上午上班高峰...  日常天气预报
6476    2018/1/8  【广州市今日天气】#天气话你知#据广州市气象台预测：今日白天：阴天，有中雨；夜间：阴天，有小...  日常天气预报
5991  2017/12/18  【广州午间天气预报】#天气话你知#据广州市气象台监测：目前，广州市晴间多云。

In [94]:
X = rcyb.loc[:, ['text']]

In [95]:
X.shape

(1092, 1)

In [96]:
X.head()

text
id                                                     
3671  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市有阵雨，并伴...
3591                                             大家注意啦！
3600  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市受台风“天鸽...
3605  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：阴天，有...
3688  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市多云...

In [97]:
X.dtypes

text    object
dtype: object

In [98]:
X.text.describe()

count                                                  1092
unique                                                 1089
top       【广州上班天气】#天气话你知#据广州市气象台预测：目前我市晴到多云。预计今天上午上班高峰期，...
freq                                                      2
Name: text, dtype: object

In [99]:
import jieba

In [100]:
def chinese_word_cut(mytext):
    return ' '.join(jieba.cut(mytext))

In [101]:
jieba.load_userdict("userdict_weibo.txt")

In [102]:
%%time
X['cutted_text'] = X.text.apply(chinese_word_cut)

Wall time: 1.55 s


In [103]:
X.head()

text  \
id                                                        
3671  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市有阵雨，并伴...   
3591                                             大家注意啦！   
3600  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市受台风“天鸽...   
3605  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：阴天，有...   
3688  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市多云...   

                                            cutted_text  
id                                                       
3671  http : / / t . cn / h91BSI 【 广州上班天气 】 据 广州市 气象...  
3591                                          大家 注意 啦 ！  
3600  http : / / t . cn / h91BSI 【 广州上班天气 】 据 广州市 气象...  
3605  http : / / t . cn / h91BSI 【 广州市今日天气 】 据 广州市 气...  
3688  http : / / t . cn / h91BSI 【 广州午间天气预报 】 据 广州市 ...

In [104]:
X.shape

(1092, 2)

In [105]:
def get_custom_stopwords(stop_words_file):
    with open(stop_words_file, encoding='utf-8') as f:
        stopwords = f.read( )
    stopwords_list = stopwords.split('\n')
    custom_stopwords_list = [i for i in stopwords_list]
    return custom_stopwords_list

In [106]:
stop_words_file = 'mystopwords.txt'
stopwords = get_custom_stopwords(stop_words_file)

In [107]:
stopwords[-10:]

['划重点', '没错', '缓慢', '增加', '务必', '较强', '辐射', '时段', '雷雨', '']

In [108]:
from sklearn.feature_extraction.text import CountVectorizer

In [109]:
vect = CountVectorizer()

In [110]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [111]:
term_matrix.head()

00  01  02  03  04  05  06  07  08  09   ...    驾驶  高峰  高峰期  高温  鸡腿  鸭肉  \
0   0   0   0   0   0   0   0   0   0   0   ...     0   0    1   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   ...     0   0    0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   ...     0   0    1   0   0   0   
3   0   0   0   0   0   0   0   1   1   0   ...     0   0    0   0   0   0   
4   1   0   0   0   0   0   0   0   1   0   ...     0   0    0   0   0   0   

   黄埔  黄埔区  黄色  黄色预警信号  
0   0    0   0       0  
1   0    0   0       0  
2   0    0   0       0  
3   0    0   0       0  
4   0    0   0       0  

[5 rows x 759 columns]

In [112]:
term_matrix.shape

(1092, 759)

In [113]:
vect = CountVectorizer(stop_words=frozenset(stopwords)) #加上停用词去除功能

In [114]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [115]:
term_matrix.head()

00  01  02  03  04  05  06  07  08  09   ...    风渐  风铃  风风  高峰期  高温  鸡腿  \
0   0   0   0   0   0   0   0   0   0   0   ...     0   0   0    1   0   0   
1   0   0   0   0   0   0   0   0   0   0   ...     0   0   0    0   0   0   
2   0   0   0   0   0   0   0   0   0   0   ...     0   0   0    1   0   0   
3   0   0   0   0   0   0   0   1   1   0   ...     0   0   0    0   0   0   
4   1   0   0   0   0   0   0   0   1   0   ...     0   0   0    0   0   0   

   鸭肉  黄埔区  黄色  黄色预警信号  
0   0    0   0       0  
1   0    0   0       0  
2   0    0   0       0  
3   0    0   0       0  
4   0    0   0       0  

[5 rows x 598 columns]

In [116]:
max_df = 0.8 # 在超过这一比例的文档中出现的关键词（过于平凡），去除掉。
min_df = 3 # 在地狱这一数量的文档中出现的关键词（过于独特），去除掉。

In [117]:
vect = CountVectorizer(max_df=max_df,
                      min_df=min_df,
                      token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                      stop_words=frozenset(stopwords))

In [118]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [119]:
term_matrix.head()

上班  下班  不利  东北风  东南风  东风  中午  中度  中心  中雨 ...   零星小雨  雷电  雷阵雨  预报  预测  预警  \
0   1   0   0    0    1   0   0   0   0   0 ...      0   0    0   0   1   0   
1   0   0   0    0    0   0   0   0   0   0 ...      0   0    0   0   0   0   
2   1   0   0    0    0   0   0   0   0   0 ...      0   0    3   0   1   0   
3   0   0   0    0    0   1   0   0   0   0 ...      0   0    0   0   1   0   
4   0   0   0    0    0   0   0   0   0   0 ...      0   0    0   0   0   0   

   风力  高峰期  高温  黄埔区  
0   0    1   0    0  
1   0    0   0    0  
2   0    1   0    0  
3   0    0   0    0  
4   0    0   0    0  

[5 rows x 114 columns]

In [120]:
n_features = 1000

In [121]:
tf_vectorizer = CountVectorizer(max_features=n_features,
                               max_df=max_df,
                               min_df=min_df,
                               token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                               stop_words=frozenset(stopwords))

In [122]:
term_matrix = pd.DataFrame(tf_vectorizer.fit_transform(X.cutted_text).toarray(), columns=tf_vectorizer.get_feature_names())

In [123]:
term_matrix.head()

上班  下班  不利  东北风  东南风  东风  中午  中度  中心  中雨 ...   零星小雨  雷电  雷阵雨  预报  预测  预警  \
0   1   0   0    0    1   0   0   0   0   0 ...      0   0    0   0   1   0   
1   0   0   0    0    0   0   0   0   0   0 ...      0   0    0   0   0   0   
2   1   0   0    0    0   0   0   0   0   0 ...      0   0    3   0   1   0   
3   0   0   0    0    0   1   0   0   0   0 ...      0   0    0   0   1   0   
4   0   0   0    0    0   0   0   0   0   0 ...      0   0    0   0   0   0   

   风力  高峰期  高温  黄埔区  
0   0    1   0    0  
1   0    0   0    0  
2   0    1   0    0  
3   0    0   0    0  
4   0    0   0    0  

[5 rows x 114 columns]

In [124]:
term_matrix.shape

(1092, 114)

In [125]:
tf = tf_vectorizer.fit_transform(X.cutted_text)

In [126]:
from sklearn.decomposition import LatentDirichletAllocation

In [127]:
n_topics = 5
lda = LatentDirichletAllocation(n_topics=n_topics,
                               max_iter=50,
                               learning_method='online',
                               learning_offset=50.,
                               random_state=0)

In [128]:
%%time
lda.fit(tf)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


Wall time: 24.3 s


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=50, mean_change_tol=0.001,
             n_components=10, n_jobs=1, n_topics=5, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [129]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print('Topic #%d:' % topic_idx)
        print(' '.join([feature_names[i]
                      for i in topic.argsort()[:-n_top_words -1:-1]]))
    print()

In [130]:
n_top_words = 20

In [131]:
tf_feature_names = tf_vectorizer.get_feature_names()
print_top_words(lda, tf_feature_names, n_top_words)

Topic #0:
高峰期 广州市区 预测 我市 各区 轻微 上班 广州上班天气 今天上午 天气话你知 晴到多云 交通 晴间多云 交通安全 偏北风 下班 傍晚 广州下班天气 不利 有轻雾
Topic #1:
多云 阴天 各区 广州市区 高峰期 轻微 天气话你知 预测 阵雨 小雨 下班 傍晚 广州下班天气 我市 分散 和缓 偏北风 交通安全 零星小雨 雷阵雨
Topic #2:
各区 广州午间天气预报 监测 轻微 天气话你知 和缓 多云间阴 偏北风 晴间多云 阵雨 晴到多云 东风 云间 东北风 雷阵雨 偏南风 我市 南沙 城区 东南风
Topic #3:
夜间 相对湿度 广州市今日天气 预测 轻微 多云 天气话你知 雷阵雨 偏北风 和缓 阴天 晴到多云 有轻雾 多云到阴 小雨 偏南风 东南风 晴间多云 东风 分散
Topic #4:
灰霾 阵雨 短时 中度 从化区 行车 阵风 伴有 轻度 广州市区 横渡珠江 降水 雷阵雨 中雨 南沙 体感 大到暴雨 录得 交通安全 雨天



In [132]:
import pyLDAvis
import pyLDAvis.sklearn
pyLDAvis.enable_notebook()
pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

PreparedData(topic_coordinates=            Freq  cluster  topics         x         y
topic                                                
0      28.127866        1       1  0.134746  0.102318
1      26.744216        1       2  0.056025  0.152588
3      22.535470        1       3  0.132171 -0.033186
2      17.976599        1       4  0.082170 -0.221167
4       4.615849        1       5 -0.405113 -0.000552, topic_info=     Category        Freq      Term       Total  loglift  logprob
term                                                             
33    Default  872.000000        多云  872.000000  30.0000  30.0000
29    Default  866.000000        各区  866.000000  29.0000  29.0000
97    Default  575.000000        阴天  575.000000  28.0000  28.0000
47    Default  274.000000  广州午间天气预报  274.000000  27.0000  27.0000
77    Default  274.000000        监测  274.000000  26.0000  26.0000
36    Default  296.000000        夜间  296.000000  25.0000  25.0000
78    Default  289.000000      相对湿度  289.000000  24.0000  24.0000
48    Default  287.000000   广州市今日天气  287.000000  23.0000  23.0000
98    Default  286.000000        阵雨  286.000000  22.0000  22.0000
49    Default  425.000000      广州市区  425.000000  21.0000  21.0000
111   Default  412.000000       高峰期  412.000000  20.0000  20.0000
0     Default  225.000000        上班  225.000000  19.0000  19.0000
108   Default  670.000000        预测  670.000000  18.0000  18.0000
45    Default  214.000000    广州上班天气  214.000000  17.0000  17.0000
71    Default   69.000000        灰霾   69.000000  16.0000  16.0000
14    Default  216.000000      今天上午  216.000000  15.0000  15.0000
12    Default  155.000000        交通  155.000000  14.0000  14.0000
35    Default  147.000000      多云间阴  147.000000  13.0000  13.0000
51    Default  357.000000        我市  357.000000  12.0000  12.0000
59    Default  280.000000      晴间多云  280.000000  11.0000  11.0000
79    Default   41.000000        短时   41.000000  10.0000  10.0000
13    Default  179.000000      交通安全  179.000000   9.0000   9.0000
42    Default  172.000000        小雨  172.000000   8.0000   8.0000
1     Default  203.000000        下班  203.000000   7.0000   7.0000
57    Default  327.000000      晴到多云  327.000000   6.0000   6.0000
22    Default  193.000000        傍晚  193.000000   5.0000   5.0000
92    Default  814.000000        轻微  814.000000   4.0000   4.0000
46    Default  190.000000    广州下班天气  190.000000   3.0000   3.0000
15    Default   46.000000       从化区   46.000000   2.0000   2.0000
7     Default   33.000000        中度   33.000000   1.0000   1.0000
...       ...         ...       ...         ...      ...      ...
105    Topic5    6.450762        雷电    7.233362   2.9612  -4.5574
81     Topic5    6.469060        稳定    7.371785   2.9450  -4.5545
82     Topic5    5.410268        舒适    6.194223   2.9404  -4.7333
6      Topic5    5.345800        中午    6.129010   2.9390  -4.7453
25     Topic5    5.312951        区域    6.096433   2.9381  -4.7514
62     Topic5    5.262444        有强    6.047481   2.9366  -4.7610
68     Topic5    4.096785        活动    4.878756   2.9010  -5.0114
109    Topic5    4.013896        预警    4.796818   2.8975  -5.0318
73     Topic5    4.012127        生效    4.796367   2.8971  -5.0323
38     Topic5    3.978957       大暴雨    4.763387   2.8957  -5.0406
67     Topic5    9.762830      注意安全   11.869812   2.8803  -4.1430
99     Topic5   17.077501        阵风   21.903561   2.8268  -3.5838
44     Topic5    5.366456        市区    7.056376   2.8019  -4.7414
21     Topic5    5.018059        偶有    7.931069   2.6179  -4.8085
9      Topic5   12.907127        中雨   22.718641   2.5103  -3.8638
100    Topic5   13.383373        降水   23.748346   2.5022  -3.8276
94     Topic5    8.035540        较差   14.412172   2.4915  -4.3377
37     Topic5   10.398005      大到暴雨   18.988105   2.4735  -4.0800
15     Topic5   22.197541       从化区   46.356713   2.3393  -3.3216
101    Topic5    9.980915        雨天   22.078877   2.2817  -4.1209
60     Topic5    9.583418        暴雨   20.710420   2.3051  -4.1615
98     Topic5  

In [133]:
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)

In [134]:
%%time
n_topics = 3    #此处的10可以自定义
lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0)
lda.fit(tf)
print_top_words(lda, tf_feature_names, n_top_words)
pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


Topic #0:
预测 轻微 夜间 相对湿度 广州市今日天气 天气话你知 多云 晴到多云 雷阵雨 有轻雾 上班 今天上午 广州上班天气 偏北风 多云到阴 和缓 广州市区 高峰期 晴间多云 各区
Topic #1:
阴天 多云 广州市区 高峰期 各区 预测 我市 天气话你知 下班 傍晚 轻微 广州下班天气 小雨 阵雨 交通安全 偏北风 和缓 交通 分散 上班
Topic #2:
各区 广州午间天气预报 监测 轻微 天气话你知 晴间多云 多云 多云间阴 和缓 阵雨 偏北风 晴到多云 云间 雷阵雨 东风 分散 我市 东北风 偏南风 南沙

Wall time: 38.8 s


In [136]:
%%time
data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
pyLDAvis.show(data)


Note: if you're in the IPython notebook, pyLDAvis.show() is not the best command
      to use. Consider using pyLDAvis.display(), or pyLDAvis.enable_notebook().
      See more information at http://pyLDAvis.github.io/quickstart.html .

You must interrupt the kernel to end this command

Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]


127.0.0.1 - - [21/Jul/2018 21:27:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Jul/2018 21:27:42] "GET /LDAvis.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jul/2018 21:27:42] "GET /d3.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Jul/2018 21:27:42] "GET /LDAvis.js HTTP/1.1" 200 -



stopping Server...
Wall time: 49 s


## 日常预报细分主题的结果打标签

In [137]:
# Doc Topics 结果
# 通过fit_transform函数,可以得到文档主题分布,Doc_Topic distribution matrix
doctopic_matrix = lda.fit_transform(tf) # numpy.ndarray
print(doctopic_matrix)
print(doctopic_matrix.shape)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


[[ 0.01806792  0.96406133  0.01787076]
 [ 0.33333333  0.33333333  0.33333333]
 [ 0.39825303  0.57877053  0.02297644]
 ..., 
 [ 0.30608023  0.56679062  0.12712915]
 [ 0.68157014  0.29276837  0.02566149]
 [ 0.93051303  0.03416555  0.03532143]]
(1092, 3)


In [138]:
doctopic = pd.DataFrame(doctopic_matrix, columns=['日常预报：上班天气预测',
                                                  '日常预报：下班高峰天气',
                                                  '日常预报：午间天气预报'])
#注意此处的主题排序是根据print_top_words(lda, tf_feature_names, n_top_words)的关键词来确定的，而非ldavis呈现的12345，那里只是按照热度排序。
doctopic.head()

日常预报：上班天气预测  日常预报：下班高峰天气  日常预报：午间天气预报
0     0.018068     0.964061     0.017871
1     0.333333     0.333333     0.333333
2     0.398253     0.578771     0.022976
3     0.611019     0.357992     0.030989
4     0.032487     0.035524     0.931990

In [139]:
doctopic.shape

(1092, 3)

In [140]:
global collist
collist = list(doctopic.columns)

def appendmax(sr):
    one = sr.idxmax()
    maxindex = pd.Series(one)
    sr = sr.append(maxindex)
    return sr

dfe = doctopic.apply(lambda x:appendmax(x), axis=1)
dfe.columns = collist + ['所属分类']
# dfe.to_csv('cluster.csv')
dfe.head()

日常预报：上班天气预测  日常预报：下班高峰天气  日常预报：午间天气预报         所属分类
0     0.018068     0.964061     0.017871  日常预报：下班高峰天气
1     0.333333     0.333333     0.333333  日常预报：上班天气预测
2     0.398253     0.578771     0.022976  日常预报：下班高峰天气
3     0.611019     0.357992     0.030989  日常预报：上班天气预测
4     0.032487     0.035524     0.931990  日常预报：午间天气预报

In [141]:
dfe.shape

(1092, 4)

In [142]:
rcyb.head()

statdate                                               text    所属分类
id                                                                        
3671  2017/8/24  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市有阵雨，并伴...  日常天气预报
3591  2017/8/22                                             大家注意啦！  日常天气预报
3600  2017/8/23  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市受台风“天鸽...  日常天气预报
3605  2017/8/23  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：阴天，有...  日常天气预报
3688  2017/8/24  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市多云...  日常天气预报

In [143]:
rcyb.shape

(1092, 3)

In [144]:
rcyb.drop('所属分类', axis=1, inplace=True)
rcyb.shape

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


(1092, 2)

In [145]:
rcyb.head()

statdate                                               text
id                                                                
3671  2017/8/24  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市有阵雨，并伴...
3591  2017/8/22                                             大家注意啦！
3600  2017/8/23  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市受台风“天鸽...
3605  2017/8/23  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：阴天，有...
3688  2017/8/24  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市多云...

In [146]:
rcyb.to_csv('rcyb.csv', encoding='gb18030')

In [147]:
rcyb = pd.read_csv('rcyb.csv', encoding='gb18030')
rcyb.head()

id   statdate                                               text
0  3671  2017/8/24  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市有阵雨，并伴...
1  3591  2017/8/22                                             大家注意啦！
2  3600  2017/8/23  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市受台风“天鸽...
3  3605  2017/8/23  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：阴天，有...
4  3688  2017/8/24  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市多云...

In [148]:
frames = [rcyb, dfe['所属分类']]
result = pd.concat(frames, axis = 1)
result.head()

id   statdate                                               text  \
0  3671  2017/8/24  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市有阵雨，并伴...   
1  3591  2017/8/22                                             大家注意啦！   
2  3600  2017/8/23  http://t.cn/h91BSI【广州上班天气】据广州市气象台预测：目前我市受台风“天鸽...   
3  3605  2017/8/23  http://t.cn/h91BSI【广州市今日天气】据广州市气象台预测：今日白天：阴天，有...   
4  3688  2017/8/24  http://t.cn/h91BSI【广州午间天气预报】据广州市气象台监测：目前，广州市多云...   

          所属分类  
0  日常预报：下班高峰天气  
1  日常预报：上班天气预测  
2  日常预报：下班高峰天气  
3  日常预报：上班天气预测  
4  日常预报：午间天气预报

In [149]:
result.to_csv('LDA_clustered_rcyb.csv', encoding='gb18030')

In [150]:
# %%time
# n_topics = 10    #此处的10可以自定义
# lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
#                                 learning_method='online',
#                                 learning_offset=50.,
#                                 random_state=0)
# lda.fit(tf)
# print_top_words(lda, tf_feature_names, n_top_words)
# pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

# %%time
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)