# 对主题挖掘的结果进行进一步细分
## 1.读数据

In [47]:
import time
import pandas as pd

In [48]:
result = pd.read_csv('LDA_clustered_5.csv', encoding='gb18030')
result.head()

id   statdate                                               text  \
0  3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...   
1  3586  2017/8/22                                               转发微博   
2  3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...   
3  3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...   
4  3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...   

       所属分类  
0  气象灾害应急响应  
1      热带风暴  
2      热带风暴  
3      热带风暴  
4      热带风暴

In [49]:
result.set_index('id', inplace=True)
result.head()

statdate                                               text      所属分类
id                                                                          
3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...  气象灾害应急响应
3586  2017/8/22                                               转发微博      热带风暴
3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...      热带风暴
3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...      热带风暴
3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...      热带风暴

## 2. 粉丝互动主题细分

In [50]:
fshd = result.loc[result.所属分类 == '粉丝互动', :]
fshd

statdate                                               text  所属分类
id                                                                      
3644  2017/8/23                      #13号台风天鸽#  地铁4号线地面高架段恢复运营服务 ,  粉丝互动
3660  2017/8/23                 #13号台风天鸽# #随手拍广州# 应该是散发着仙气的小蛮腰@广州塔  粉丝互动
3661  2017/8/23              #13号台风天鸽# #随手拍广州# 从延时摄影回顾一下今天这只鸽子[憧憬]  粉丝互动
3662  2017/8/23                    #小编8天气# 目前有一小块回波从番禺靠近市区，小伙伴们注意啦  粉丝互动
3666  2017/8/24                            #天气话你知# 降水回波靠近海珠啦[并不简单]  粉丝互动
3667  2017/8/24    #天气话你知# 目前降水回波主要集中在南沙和番禺，以及增城从化交界，黄埔也有一点点[并不简单]  粉丝互动
3668  2017/8/24            #天气话你知# 降水回波擦到荔湾啦，而增城的回波也移向黄埔和从化了[并不简单]  粉丝互动
3709  2017/8/25  #小编精分日常#胖“天鸽”飞走，“帕卡”鱼游来。??\n小编A：台风来之前都好热，登陆了下雨...  粉丝互动
3588  2017/8/22                            #13号台风天鸽# 加密会商ING[微笑]……  粉丝互动
3596  2017/8/23  #13号台风天鸽# #小编8天气# 旋转跳跃，“天鸽”目前还闭着眼……不过可以看到它西南侧的...  粉丝互动
3598  2017/8/23  【实况播报】#天气话你知#外面的风呼呼的，外围云系甩上来，增城、番禺、南沙有雨，预计早上班期...  粉丝互动
3601  2017/8/23  【实况播报】#13号台风天鸽##天气话你知# 南沙最大阵风达到8级了，预计今日风力仍会继续加...  粉丝互动
3610  2017/8/23  【早安，广州】#天气话你知# #13号台风天鸽#天鸽已加强为强台风级，距离登陆越发靠近，南部...  粉丝互动
3619  2017/8/23  #天气话你知# #13号台风天鸽# 【要去海边的同志注意了！】8月23日10时，风暴潮叠加天...  粉丝互动
3620  2017/8/23              #13号台风天鸽# #天气话你知# 南沙风雨实况，在外的筒子还好么[允悲]  粉丝互动
3628  2017/8/23  大家注意了！#13号台风天鸽#广州地铁的最新消息：【四号线新造~黄村短线运行】受高架段停运影...  粉丝互动
3676  2017/8/24               #小编8天气# 小编这里被局部啦 http://t.cn/RCpzapD  粉丝互动
3679  2017/8/24  【早安，广州】#小编8天气# “天鸽”虽然远去，偏南气流还要作怪，一大清早任性地甩上来一波雷...  粉丝互动
3681  2017/8/24                                #随手拍广州#阴阳分野，雨后蓝天[污]  粉丝互动
3684  2017/8/24       #随手拍广州# 好大的太阳[汗]。后续还会有阵雨影响，时晴时雨，带伞防偷袭哦[笑而不语]  粉丝互动
3686  2017/8/24  #小编8天气# 市区降水已经基本结束，不过南边还有雷雨云团不断北上，天气不稳定，今天都是雨-...  粉丝互动
3687  2017/8/24                      #随手拍广州#树：在哪里被刮倒，就在哪里趴着不起来[二哈]  粉丝互动
3689  2017/8/24                         #随手拍广州# 蓝天白云，热死狗[二哈]。作者见水印  粉丝互动
3690  2017/8/24                                 #小编8科普#先转了再说[doge]  粉丝互动
3691  2017/8/24  http://t.cn/h91BSI【七天天气预报—降水日趋明显】“天鸽”总算远去，雷雨又将...  粉丝互动
3692  2017/8/24  #小编8天气# 海上代有台风出，一代新台换旧台[允悲]。13号台风刚刚远去，太平洋上又有新扰...  粉丝互动
3695  2017/8/24            #小编8天气# 荔湾、白云、花都的小伙伴注意，泥萌的下班雨，到货了[doge]  粉丝互动
3697  2017/8/24  #小编8天气# 喏，你们要的准14号台风宝宝[doge]。小编只希望它半路夭折，别来祸害广东...  粉丝互动
3698  2017/8/24               #小编8天气# 增城，从化的雨下了挺长时间了[汗]。那边的小伙伴还好吗？  粉丝互动
3559  2017/8/22                     #小编8天气# 被局部的和没被局部的，请自行感受[微笑]……  粉丝互动
...         ...                                                ...   ...
6534   2018/1/9       #小编8天气#天气那么冷，后山的喵子居然出来了，为了撸猫，小编冻得鼻涕直流~~~[允悲]  粉丝互动
6536   2018/1/9  从评论上看，泥萌是真的不想要小编手写的祝福语明信片[允悲]//@广州天气: #天气福利#话说...  粉丝互动
6537   2018/1/9  #天气话你知#气温就像一条蛇，终于抬头了~~周杰伦《蜗牛-周杰伦》 http://t.cn/...  粉丝互动
6538   2018/1/9  《今天的广州塔为什么看不到雪？》 本次寒潮横扫广东，粤北多地下雪和冰冻，于是大家就盼望着近6...  粉丝互动
6539   2018/1/9  【七天天气预报-终于可以晾干衣服了】 #天气话你知# 昨天到今天，我们大咩咩城那是冷雨铺面，...  粉丝互动
6540   2018/1/9  几个小编都按规矩转了，每次抽奖都转，然而从来都没有小编中过[摊手]就是这么公平[二哈]//@...  粉丝互动
6541   2018/1/9  恭喜@Ferry178-OH 等25名用户获得【乖乖云声光控小夜灯】, @小婕婕醬oO 等2...  粉丝互动
3402  2017/8/15                             #随手拍广州# 街头巷尾都是生活[心][心]  粉丝互动
3403  2017/8/15                                       #随手拍广州# [爱你]  粉丝互动
3404  2017/8/15                                 #随手拍广州# 夏天傍晚的广州[心]  粉丝互动
3405  2017/8/16                                 #随手拍广州# 美丽朝霞[心][心]  粉丝互动
3406  2017/8/16  #随手拍广州# 早起的人儿有美景看[小黄人坏笑]。美丽的早晨，预计上下班时段大广州没雨，安心...  粉丝互动
3409  2017/8/16  【早安，广州】#随手拍广州#有吃货粉丝说，今天的云像是撕开的面包丝[笑cry]。云霞如此美腻...  粉丝互动
3410  2017/8/16  #小编8天气# 副高减退，久违的雷雨又在海上现身，午后广州发生雷雨的可能性很高哦。晒被子的，...  粉丝互动
3411  2017/8/16                                 早[doge]天热多喝水[doge]  粉丝互动
3412  2017/8/16  #小编8天气# 降雨回波自南向北，从海上越发加强逼近广州了[doge]。泥萌都是聪明粉儿，快...  粉丝互动
3414  2017/8/16  #小编8天气# 受局地雷雨影响，热辣烤鸡腿的根部已褪色。雷雨会继续北推影响市区，黄埔南部也有...  粉丝互动
3417  2017/8/16                  #小编8天气# 南沙榄核附近局地雷雨生成，番禺的小伙伴也要注意哦~  粉丝互动
3418  2017/8/16       #随手拍广州#午后局地雷雨还没来，先送大家两张超美的图片[憧憬]。感谢两位拍摄者，见水印  粉丝互动
3419  2017/8/16                                               [允悲]  粉丝互动
3420  2017/8/16  #小编8天气# 影响市区的局地雷雨已经过去，大家不用等了[允悲]。小谷围和长洲的童鞋们有被淋...  粉丝互动
3424  2017/8/16  【七天天气预报—副高魔王很任性】受西伸加强的副高边缘影响，明日仍有局地雷雨打扰，有幸被“局”..

In [51]:
X = fshd.loc[:, ['text']]

In [52]:
X.shape

(4560, 1)

In [53]:
X.head()

text
id                                         
3644          #13号台风天鸽#  地铁4号线地面高架段恢复运营服务 ,
3660     #13号台风天鸽# #随手拍广州# 应该是散发着仙气的小蛮腰@广州塔
3661  #13号台风天鸽# #随手拍广州# 从延时摄影回顾一下今天这只鸽子[憧憬]
3662        #小编8天气# 目前有一小块回波从番禺靠近市区，小伙伴们注意啦
3666                #天气话你知# 降水回波靠近海珠啦[并不简单]

In [54]:
X.dtypes

text    object
dtype: object

In [55]:
X.text.describe()

count        4560
unique       4532
top       #随手拍广州#
freq           14
Name: text, dtype: object

In [56]:
import jieba

In [57]:
def chinese_word_cut(mytext):
    return ' '.join(jieba.cut(mytext))

In [58]:
jieba.load_userdict("userdict_weibo.txt")

In [59]:
%%time
X['cutted_text'] = X.text.apply(chinese_word_cut)

Wall time: 2.04 s


In [60]:
X.head()

text  \
id                                            
3644          #13号台风天鸽#  地铁4号线地面高架段恢复运营服务 ,   
3660     #13号台风天鸽# #随手拍广州# 应该是散发着仙气的小蛮腰@广州塔   
3661  #13号台风天鸽# #随手拍广州# 从延时摄影回顾一下今天这只鸽子[憧憬]   
3662        #小编8天气# 目前有一小块回波从番禺靠近市区，小伙伴们注意啦   
3666                #天气话你知# 降水回波靠近海珠啦[并不简单]   

                                            cutted_text  
id                                                       
3644       # 13号台风天鸽 #     地铁 4 号线 地面 高架 段 恢复 运营 服务   ,  
3660  # 13号台风天鸽 #   # 随手拍广州 #   应该 是 散发 着 仙气 的 小蛮 腰 ...  
3661  # 13号台风天鸽 #   # 随手拍广州 #   从 延时 摄影 回顾 一下 今天 这 只...  
3662    # 小编8天气 #   目前 有 一小块 回波 从 番禺 靠近 市区 ， 小伙伴 们 注意 啦  
3666               # 天气话你知 #   降水 回波 靠近 海珠 啦 [ 并 不 简单 ]

In [61]:
X.shape

(4560, 2)

In [62]:
def get_custom_stopwords(stop_words_file):
    with open(stop_words_file, encoding='utf-8') as f:
        stopwords = f.read( )
    stopwords_list = stopwords.split('\n')
    custom_stopwords_list = [i for i in stopwords_list]
    return custom_stopwords_list

In [63]:
stop_words_file = 'mystopwords.txt'
stopwords = get_custom_stopwords(stop_words_file)

In [64]:
stopwords[-10:]

['没错', '缓慢', '增加', '务必', '较强', '辐射', '时段', '雷雨', '', '']

In [65]:
from sklearn.feature_extraction.text import CountVectorizer

In [66]:
vect = CountVectorizer()

In [67]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [68]:
term_matrix.head()

00  0125  02  03  062  07  08  0818  09  0929 ...  齐心  齐飞  龐爺  龙卷  龙岩  龙江  \
0   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   
1   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   
2   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   
3   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   
4   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   

   龙胜  龙舟  龙虾  龟速  
0   0   0   0   0  
1   0   0   0   0  
2   0   0   0   0  
3   0   0   0   0  
4   0   0   0   0  

[5 rows x 10825 columns]

In [69]:
term_matrix.shape

(4560, 10825)

In [70]:
vect = CountVectorizer(stop_words=frozenset(stopwords)) #加上停用词去除功能

In [71]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [72]:
term_matrix.head()

00  0125  02  03  062  07  08  0818  09  0929 ...  齐心  齐飞  龐爺  龙卷  龙岩  龙江  \
0   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   
1   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   
2   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   
3   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   
4   0     0   0   0    0   0   0     0   0     0 ...   0   0   0   0   0   0   

   龙胜  龙舟  龙虾  龟速  
0   0   0   0   0  
1   0   0   0   0  
2   0   0   0   0  
3   0   0   0   0  
4   0   0   0   0  

[5 rows x 10069 columns]

In [73]:
max_df = 0.8 # 在超过这一比例的文档中出现的关键词（过于平凡），去除掉。
min_df = 3 # 在地狱这一数量的文档中出现的关键词（过于独特），去除掉。

In [74]:
vect = CountVectorizer(max_df=max_df,
                      min_df=min_df,
                      token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                      stop_words=frozenset(stopwords))

In [75]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

D:\Anaconda3\lib\site-packages\_pytest\fixtures.py:844: DeprecationWarning: The `convert` argument is deprecated in favor of `converter`.  It will be removed after 2019/01.
  params = attr.ib(convert=attr.converters.optional(tuple))
D:\Anaconda3\lib\site-packages\_pytest\fixtures.py:846: DeprecationWarning: The `convert` argument is deprecated in favor of `converter`.  It will be removed after 2019/01.
  ids = attr.ib(default=None, convert=_ensure_immutable_ids)


MemoryError: 

In [ ]:
term_matrix.head()

In [ ]:
n_features = 1000

In [ ]:
tf_vectorizer = CountVectorizer(max_features=n_features,
                               max_df=max_df,
                               min_df=min_df,
                               token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                               stop_words=frozenset(stopwords))

In [ ]:
term_matrix = pd.DataFrame(tf_vectorizer.fit_transform(X.cutted_text).toarray(), columns=tf_vectorizer.get_feature_names())

In [ ]:
term_matrix.head()

In [ ]:
term_matrix.shape

In [36]:
tf = tf_vectorizer.fit_transform(X.cutted_text)

In [37]:
from sklearn.decomposition import LatentDirichletAllocation

In [38]:
n_topics = 5
lda = LatentDirichletAllocation(n_topics=n_topics,
                               max_iter=50,
                               learning_method='online',
                               learning_offset=50.,
                               random_state=0)

In [39]:
%%time
lda.fit(tf)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


Wall time: 48.8 s


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=50, mean_change_tol=0.001,
             n_components=10, n_jobs=1, n_topics=5, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [40]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print('Topic #%d:' % topic_idx)
        print(' '.join([feature_names[i]
                      for i in topic.argsort()[:-n_top_words -1:-1]]))
    print()

In [41]:
n_top_words = 20

In [42]:
tf_feature_names = tf_vectorizer.get_feature_names()
print_top_words(lda, tf_feature_names, n_top_words)

Topic #0:
不语 太阳 小编8天气 气象 生病 鼓掌 抽奖 秒拍 视频 微博 r2wjcgp 阳光 小可爱 天气君撸猫日常 转发 奖品 doge 春节 一片 加油
Topic #1:
天气话你知 天气预报 冷空气 七天 早安 简单 小编8天气 摊手 几天 阳光 早晚 不语 出门 最高 温度 防晒 比较 高温 二哈 记得
Topic #2:
天气话你知 小编8天气 微笑 降水 广州春运天气 出门 晚上 小伙伴 南沙 预警 市区 简单 广东 记得 上班 中国 交通安全 带伞 注意安全 留意
Topic #3:
随手拍广州 二哈 小编8天气 小编 泥萌 doge 吃瓜 摊手 天气话你知 外套 可爱 阳光 鸡腿 允悲 长袖 短袖 开心 cry 早安 喜欢
Topic #4:
小编8天气 小编 憧憬 晚安 允悲 doge 简单 回波 首席 月亮 小伙伴 摊手 降水 下雨 二哈 局地 r2wjcgp 白云 cry 阴险



In [43]:
import pyLDAvis
import pyLDAvis.sklearn
pyLDAvis.enable_notebook()
pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]


PreparedData(topic_coordinates=            Freq  cluster  topics         x         y
topic                                                
1      32.044545        1       1 -0.088006 -0.035264
4      21.179929        1       2 -0.064475  0.080789
3      18.401515        1       3 -0.045440  0.274496
2      16.651929        1       4 -0.166222 -0.247210
0      11.722081        1       5  0.364143 -0.072810, topic_info=     Category         Freq     Term        Total  loglift  logprob
term                                                              
939   Default   792.000000    随手拍广州   792.000000  30.0000  30.0000
65    Default   741.000000       不语   741.000000  29.0000  29.0000
383   Default   694.000000       小编   694.000000  28.0000  28.0000
456   Default   366.000000       憧憬   366.000000  27.0000  27.0000
92    Default   532.000000       二哈   532.000000  26.0000  26.0000
538   Default   294.000000       晚安   294.000000  25.0000  25.0000
337   Default   972.000000    天气话你知   972.000000  24.0000  24.0000
344   Default   211.000000       太阳   211.000000  23.0000  23.0000
338   Default   328.000000     天气预报   328.000000  22.0000  22.0000
180   Default   317.000000      冷空气   317.000000  21.0000  21.0000
36    Default   307.000000       七天   307.000000  20.0000  20.0000
294   Default   218.000000       回波   218.000000  19.0000  19.0000
157   Default   404.000000       允悲   404.000000  18.0000  18.0000
985   Default   198.000000       首席   198.000000  17.0000  17.0000
432   Default   161.000000       微笑   161.000000  16.0000  16.0000
384   Default  1216.000000    小编8天气  1216.000000  15.0000  15.0000
628   Default   222.000000       泥萌   222.000000  14.0000  14.0000
935   Default   292.000000       降水   292.000000  13.0000  13.0000
565   Default   152.000000       月亮   152.000000  12.0000  12.0000
749   Default   502.000000       简单   502.000000  11.0000  11.0000
412   Default   176.000000   广州春运天气   176.000000  10.0000  10.0000
262   Default   211.000000       吃瓜   211.000000   9.0000   9.0000
511   Default   292.000000       早安   292.000000   8.0000   8.0000
315   Default   147.000000       外套   147.000000   7.0000   7.0000
258   Default   101.000000       可爱   101.000000   6.0000   6.0000
192   Default   277.000000       出门   277.000000   5.0000   5.0000
537   Default    92.000000       晚上    92.000000   4.0000   4.0000
377   Default   290.000000      小伙伴   290.000000   3.0000   3.0000
4     Default   560.000000     doge   560.000000   2.0000   2.0000
922   Default   266.000000       阳光   266.000000   1.0000   1.0000
...       ...          ...      ...          ...      ...      ...
860    Topic5    36.891229       转发    37.670462   2.1228  -4.6574
347    Topic5    35.679588       奖品    36.455423   2.1222  -4.6908
530    Topic5    29.903361       春节    30.689433   2.1177  -4.8674
207    Topic5    28.866508       加油    29.648934   2.1170  -4.9027
29     Topic5    29.148541       一片    29.940590   2.1169  -4.8929
612    Topic5    26.472605   气象汪的日常    27.250864   2.1147  -4.9892
214    Topic5    26.692929       北边    27.484687   2.1145  -4.9809
804    Topic5    25.042858       获得    25.818529   2.1132  -5.0448
48     Topic5    24.185623       下载    24.959939   2.1122  -5.0796
633    Topic5    22.891547       洗澡    23.671014   2.1102  -5.1346
984    Topic5    22.862536       馋嘴    23.643622   2.1101  -5.1358
166    Topic5    22.849039       公公    23.632169   2.1100  -5.1364
684    Topic5    21.887741       现场    22.670855   2.1085  -5.1794
283    Topic5    21.427689     嗨森一刻    22.205652   2.1080  -5.2007
390    Topic5    21.106618       小黑    21.883754   2.1075  -5.2158
336    Topic5    20.994000     天气福利    21.769355   2.1074  -5.2211
766    Topic5    20.717456       给力    21.502155   2.1065  -5.2344
135    Topic5    20.513082       使用    21.291712   2.1064  -5.2443
689    Topic5    19.894899       用户    20.670412   2.1055  -5.2749
417    Topic5    18.444018       开奖    19.219979   2.1025  -5.3506
775    Topic5    18.391976  

In [44]:
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)

In [45]:
%%time
n_topics = 5    #此处的10可以自定义
lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0)
lda.fit(tf)
print_top_words(lda, tf_feature_names, n_top_words)
pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


Topic #0:
不语 太阳 小编8天气 气象 生病 鼓掌 抽奖 秒拍 视频 微博 r2wjcgp 阳光 小可爱 天气君撸猫日常 转发 奖品 doge 春节 一片 加油
Topic #1:
天气话你知 天气预报 冷空气 七天 早安 简单 小编8天气 摊手 几天 阳光 早晚 不语 出门 最高 温度 防晒 比较 高温 二哈 记得
Topic #2:
天气话你知 小编8天气 微笑 降水 广州春运天气 出门 晚上 小伙伴 南沙 预警 市区 简单 广东 记得 上班 中国 交通安全 带伞 注意安全 留意
Topic #3:
随手拍广州 二哈 小编8天气 小编 泥萌 doge 吃瓜 摊手 天气话你知 外套 可爱 阳光 鸡腿 允悲 长袖 短袖 开心 cry 早安 喜欢
Topic #4:
小编8天气 小编 憧憬 晚安 允悲 doge 简单 回波 首席 月亮 小伙伴 摊手 降水 下雨 二哈 局地 r2wjcgp 白云 cry 阴险



D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]


Wall time: 54.3 s


In [46]:
%%time
data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
pyLDAvis.show(data)

D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]



Note: if you're in the IPython notebook, pyLDAvis.show() is not the best command
      to use. Consider using pyLDAvis.display(), or pyLDAvis.enable_notebook().
      See more information at http://pyLDAvis.github.io/quickstart.html .

You must interrupt the kernel to end this command

Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]


127.0.0.1 - - [23/Jul/2018 16:36:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Jul/2018 16:36:50] "GET /LDAvis.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Jul/2018 16:36:50] "GET /d3.js HTTP/1.1" 200 -
127.0.0.1 - - [23/Jul/2018 16:36:50] "GET /LDAvis.js HTTP/1.1" 200 -



stopping Server...
Wall time: 3min 45s


## 3. 粉丝互动细分主题的结果打标签

In [72]:
# Doc Topics 结果
# 通过fit_transform函数,可以得到文档主题分布,Doc_Topic distribution matrix
doctopic_matrix = lda.fit_transform(tf) # numpy.ndarray
print(doctopic_matrix)
print(doctopic_matrix.shape)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


[[ 0.54950045  0.05000054  0.0506242   0.299874    0.05000081]
 [ 0.10000004  0.10000001  0.10000002  0.5999999   0.10000003]
 [ 0.29979373  0.05000048  0.05000093  0.30011571  0.30008916]
 ..., 
 [ 0.06695956  0.06975208  0.06691382  0.72819017  0.06818437]
 [ 0.02894936  0.63300601  0.02878157  0.27998413  0.02927894]
 [ 0.11872695  0.02610412  0.02563834  0.02504256  0.80448804]]
(4560, 5)


In [73]:
doctopic = pd.DataFrame(doctopic_matrix, columns=['粉丝互动：奖品福利', 
                                                  '粉丝互动：出行提醒',
                                                  '粉丝互动：春运天气',
                                                  '粉丝互动：随手拍广州',
                                                  '粉丝互动：首席小编互动'])
#注意此处的主题排序是根据print_top_words(lda, tf_feature_names, n_top_words)的关键词来确定的，而非ldavis呈现的12345，那里只是按照热度排序。
doctopic.head()

粉丝互动：奖品福利  粉丝互动：出行提醒  粉丝互动：春运天气  粉丝互动：随手拍广州  粉丝互动：首席小编互动
0   0.549500   0.050001   0.050624    0.299874     0.050001
1   0.100000   0.100000   0.100000    0.600000     0.100000
2   0.299794   0.050000   0.050001    0.300116     0.300089
3   0.033415   0.033455   0.033918    0.033408     0.865804
4   0.033333   0.034407   0.295119    0.033617     0.603523

In [74]:
doctopic.shape

(4560, 5)

In [75]:
global collist
collist = list(doctopic.columns)

def appendmax(sr):
    one = sr.idxmax()
    maxindex = pd.Series(one)
    sr = sr.append(maxindex)
    return sr

dfe = doctopic.apply(lambda x:appendmax(x), axis=1)
dfe.columns = collist + ['所属分类']
# dfe.to_csv('cluster.csv')
dfe.head()

粉丝互动：奖品福利  粉丝互动：出行提醒  粉丝互动：春运天气  粉丝互动：随手拍广州  粉丝互动：首席小编互动         所属分类
0   0.549500   0.050001   0.050624    0.299874     0.050001    粉丝互动：奖品福利
1   0.100000   0.100000   0.100000    0.600000     0.100000   粉丝互动：随手拍广州
2   0.299794   0.050000   0.050001    0.300116     0.300089   粉丝互动：随手拍广州
3   0.033415   0.033455   0.033918    0.033408     0.865804  粉丝互动：首席小编互动
4   0.033333   0.034407   0.295119    0.033617     0.603523  粉丝互动：首席小编互动

In [76]:
dfe.shape

(4560, 6)

In [77]:
fshd.drop('所属分类', axis=1, inplace=True)
fshd.shape

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


(4560, 2)

In [78]:
fshd.to_csv('fshd.csv', encoding='gb18030')

In [79]:
fshd = pd.read_csv('fshd.csv', encoding='gb18030')
fshd.head()

id   statdate                                   text
0  3644  2017/8/23          #13号台风天鸽#  地铁4号线地面高架段恢复运营服务 ,
1  3660  2017/8/23     #13号台风天鸽# #随手拍广州# 应该是散发着仙气的小蛮腰@广州塔
2  3661  2017/8/23  #13号台风天鸽# #随手拍广州# 从延时摄影回顾一下今天这只鸽子[憧憬]
3  3662  2017/8/23        #小编8天气# 目前有一小块回波从番禺靠近市区，小伙伴们注意啦
4  3666  2017/8/24                #天气话你知# 降水回波靠近海珠啦[并不简单]

In [80]:
frames = [fshd, dfe['所属分类']]
result = pd.concat(frames, axis = 1)
result.head()

id   statdate                                   text         所属分类
0  3644  2017/8/23          #13号台风天鸽#  地铁4号线地面高架段恢复运营服务 ,    粉丝互动：奖品福利
1  3660  2017/8/23     #13号台风天鸽# #随手拍广州# 应该是散发着仙气的小蛮腰@广州塔   粉丝互动：随手拍广州
2  3661  2017/8/23  #13号台风天鸽# #随手拍广州# 从延时摄影回顾一下今天这只鸽子[憧憬]   粉丝互动：随手拍广州
3  3662  2017/8/23        #小编8天气# 目前有一小块回波从番禺靠近市区，小伙伴们注意啦  粉丝互动：首席小编互动
4  3666  2017/8/24                #天气话你知# 降水回波靠近海珠啦[并不简单]  粉丝互动：首席小编互动

In [81]:
result.to_csv('LDA_clustered_fshd.csv', encoding='gb18030')

In [57]:
# %%time
# n_topics = 10    #此处的10可以自定义
# lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
#                                 learning_method='online',
#                                 learning_offset=50.,
#                                 random_state=0)
# lda.fit(tf)
# print_top_words(lda, tf_feature_names, n_top_words)
# pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

# %%time
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)