# 对主题挖掘的结果进行进一步细分

In [1]:
import time
import pandas as pd
%matplotlib inline

In [2]:
result = pd.read_csv('LDA_clustered_5.csv', encoding='gb18030')
result.head()

id   statdate                                               text  \
0  3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...   
1  3586  2017/8/22                                               转发微博   
2  3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...   
3  3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...   
4  3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...   

       所属分类  
0  气象灾害应急响应  
1      热带风暴  
2      热带风暴  
3      热带风暴  
4      热带风暴

In [3]:
result.set_index('id', inplace=True)
result.head()

statdate                                               text      所属分类
id                                                                          
3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...  气象灾害应急响应
3586  2017/8/22                                               转发微博      热带风暴
3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...      热带风暴
3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...      热带风暴
3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...      热带风暴

## 热带风暴主题细分

In [4]:
rdfb = result.loc[result.所属分类 == '热带风暴', :]
rdfb

statdate                                               text  所属分类
id                                                                       
3586   2017/8/22                                               转发微博  热带风暴
3641   2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...  热带风暴
3642   2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...  热带风暴
3643   2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...  热带风暴
3645   2017/8/23                                               转发微博  热带风暴
3646   2017/8/23                                               转发微博  热带风暴
3647   2017/8/23                                               转发微博  热带风暴
3648   2017/8/23                                               转发微博  热带风暴
3649   2017/8/23  #天气话你知##13号台风天鸽# “天鸽”的主风区和主雨区随着台风中心的西移而西移，广州范围...  热带风暴
3650   2017/8/23                                               转发微博  热带风暴
3651   2017/8/23  http://t.cn/h91BSI【台风预警信号解除】受“天鸽”影响，今天白天广州市区普遍...  热带风暴
3652   2017/8/23                                               转发微博  热带风暴
3653   2017/8/23                                               转发微博  热带风暴
3654   2017/8/23                                               转发微博  热带风暴
3655   2017/8/23  http://t.cn/h91BSI【台风消息】今天20时，台风“天鸽”（强热带风暴级）中心...  热带风暴
3656   2017/8/23                                               转发微博  热带风暴
3657   2017/8/23                                               转发微博  热带风暴
3659   2017/8/23                                               转发微博  热带风暴
3670   2017/8/24                                               转发微博  热带风暴
3706   2017/8/25  http://t.cn/h91BSI【台风消息】25日08时，今年第14号台风“帕卡”（热带...  热带风暴
3707   2017/8/25  【早安，广州】#天气话你知##台风帕卡# 13号台风“天鸽”飞走了，14号台风“帕卡”生成[...  热带风暴
3708   2017/8/25  #小编8天气#希望各台风都保住自己的“名字”，争取当优秀的台风。 http://t.cn/R...  热带风暴
3587   2017/8/22  http://t.cn/h91BSI【台风警报】今天20时，台风“天鸽”（台风级）中心位于广...  热带风暴
3590   2017/8/22  #13号台风天鸽# 【台风最新消息】今天晚上10时，今年第13号台风"天鸽"（台风级）中心位...  热带风暴
3592   2017/8/22  #13号台风天鸽# 【台风最新消息】今天晚上9时，今年第13号台风"天鸽"（台风级）中心位于...  热带风暴
3593   2017/8/23  #13号台风天鸽#【台风最新消息】今天凌晨4时，今年第13号台风"天鸽"（台风级）中心位于北...  热带风暴
3594   2017/8/23  #13号台风天鸽#【台风最新消息】今天凌晨3时，今年第13号台风"天鸽"（台风级）中心位于北...  热带风暴
3595   2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天02时，台风“天鸽”（台风级）中心位...  热带风暴
3597   2017/8/23  #13号台风天鸽# 【台风最新消息】今天半夜1时，今年第13号台风"天鸽"（台风级）中心位于...  热带风暴
3599   2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天05时，台风“天鸽”（台风级）中心位...  热带风暴
...          ...                                                ...   ...
2652   2017/7/14                                               转发微博  热带风暴
2653   2017/7/14                                               转发微博  热带风暴
2654   2017/7/14                                               转发微博  热带风暴
2655   2017/7/14  【广州气象快报】12日以来我市维持晴热高温天气，最高气温在34～36℃。目前在西沙群岛附近的...  热带风暴
2657   2017/7/14                                               转发微博  热带风暴
2153   2017/6/23                     #随手拍广州# 风雨过后见彩虹[赞]。转发此条锦鲤[哈哈]。  热带风暴
2155   2017/6/23                                               转发微博  热带风暴
2156   2017/6/23                                               转发微博  热带风暴
8295   2018/3/20                   夜来风雨声，花落知多少~@crazy_susan @天使忍住眼泪  热带风暴
8299   2018/3/20                     一等奖价值1000呢~大家赶紧转发告诉自己认识的摄影爱好者呀  热带风暴
7914    2018/3/4                             《踏上新征程》MV三分钟讲述广东人民幸福生活  热带风暴
2867   2017/7/24                                               转发微博  热带风暴
2204   2017/6/26                                               转发微博  热带风暴
2215   2017/6/27                           还有手环，最后还有一个移动电源的上墙名额[二哈]  热带风暴
2217   2017/6/27                                               转发微博  热带风暴
3494   2017/8/20  http://t.cn/h91BSI【台风消息】20日14时，台湾东南洋面的热带低压加强为今...  热带风暴
3495   2017/8/20     【13号台风】#天气话你知# 14时，13号台风（热带风暴级）诞生了~~暂时没有名字[摊手]  热带风暴
3501   2017/8/20  http://t.cn/h91BSI【台风消息】20日20时，今年第13号台风“天鸽”（热带...  热带风暴
3505   2017/8/21  http://t.cn/h91BSI【台风消息】21日08时，今年第13号台风“天鸽”（热带...  热带风暴
5986  2017/12/18                                  看雪何必到北方，虽然这是霜[二哈]  热带风暴
3401   2017/8/15                                               转发微博  热带风暴
3415   2017/

In [5]:
X = rdfb.loc[:, ['text']]

In [6]:
X.shape

(409, 1)

In [7]:
X.head()

text
id                                                     
3586                                               转发微博
3641  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...
3642  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...
3643  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...
3645                                               转发微博

In [8]:
X.dtypes

text    object
dtype: object

In [9]:
X.text.describe()

count      409
unique     271
top       转发微博
freq       139
Name: text, dtype: object

In [10]:
import jieba

In [11]:
def chinese_word_cut(mytext):
    return ' '.join(jieba.cut(mytext))

In [12]:
jieba.load_userdict("userdict_weibo.txt")

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\1\jieba.cache
Loading model cost 1.519 seconds.
Prefix dict has been built succesfully.


In [13]:
%%time
X['cutted_text'] = X.text.apply(chinese_word_cut)

Wall time: 513 ms


In [14]:
X.head()

text  \
id                                                        
3586                                               转发微博   
3641  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...   
3642  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...   
3643  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...   
3645                                               转发微博   

                                            cutted_text  
id                                                       
3586                                              转发 微博  
3641  http : / / t . cn / h91BSI 【 台风 紧急警报 】 今天下午 16...  
3642  【 七天 天气预报 — “ 天鸽 ” 上岸 ， 仍 有 风雨 】 # 天气话你知 #   #...  
3643  http : / / t . cn / h91BSI 【 台风 蓝色 预警 信号 】 今年 ...  
3645                                              转发 微博

In [15]:
X.shape

(409, 2)

In [16]:
def get_custom_stopwords(stop_words_file):
    with open(stop_words_file, encoding='utf-8') as f:
        stopwords = f.read( )
    stopwords_list = stopwords.split('\n')
    custom_stopwords_list = [i for i in stopwords_list]
    return custom_stopwords_list

In [17]:
stop_words_file = 'mystopwords.txt'
stopwords = get_custom_stopwords(stop_words_file)

In [18]:
stopwords[-10:]

['划重点', '没错', '缓慢', '增加', '务必', '较强', '辐射', '时段', '雷雨', '']

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
vect = CountVectorizer()

In [21]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [22]:
term_matrix.head()

01  02  04  05  06  07  08  09  10  100 ...  鹅銮鼻  黄人  黄人坏  黄埔  黄埔区  黄色  \
0   0   0   0   0   0   0   0   0   0    0 ...    0   0    0   0    0   0   
1   0   0   0   0   0   0   0   0   0    0 ...    0   0    0   0    0   0   
2   0   0   0   0   0   0   0   0   0    0 ...    0   0    0   0    0   0   
3   0   0   0   0   0   0   0   0   0    0 ...    0   0    0   0    0   0   
4   0   0   0   0   0   0   0   0   0    0 ...    0   0    0   0    0   0   

   黄色预警信号  黑暗  鼓掌  齐飞  
0       0   0   0   0  
1       0   0   0   0  
2       0   0   0   0  
3       0   0   0   0  
4       0   0   0   0  

[5 rows x 1412 columns]

In [23]:
term_matrix.shape

(409, 1412)

In [24]:
vect = CountVectorizer(stop_words=frozenset(stopwords)) #加上停用词去除功能

In [25]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [26]:
term_matrix.head()

01  02  04  05  06  07  08  09  10  100 ...  鸽子  鹅銮鼻  黄人  黄人坏  黄埔区  黄色  \
0   0   0   0   0   0   0   0   0   0    0 ...   0    0   0    0    0   0   
1   0   0   0   0   0   0   0   0   0    0 ...   0    0   0    0    0   0   
2   0   0   0   0   0   0   0   0   0    0 ...   0    0   0    0    0   0   
3   0   0   0   0   0   0   0   0   0    0 ...   0    0   0    0    0   0   
4   0   0   0   0   0   0   0   0   0    0 ...   0    0   0    0    0   0   

   黄色预警信号  黑暗  鼓掌  齐飞  
0       0   0   0   0  
1       0   0   0   0  
2       0   0   0   0  
3       0   0   0   0  
4       0   0   0   0  

[5 rows x 1156 columns]

In [27]:
max_df = 0.8 # 在超过这一比例的文档中出现的关键词（过于平凡），去除掉。
min_df = 3 # 在地狱这一数量的文档中出现的关键词（过于独特），去除掉。

In [28]:
vect = CountVectorizer(max_df=max_df,
                      min_df=min_df,
                      token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                      stop_words=frozenset(stopwords))

In [29]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [30]:
term_matrix.head()

baby  doge  r2tuaac  一带  七夕  七天  三亚市  上岸  下沉  不语   ...    预警  风力  风速  风雨  \
0     0     0        0   0   0   0    0   0   0   0   ...     0   0   0   0   
1     0     0        0   0   0   0    0   0   0   0   ...     0   1   0   0   
2     0     0        0   0   0   1    0   1   0   0   ...     0   0   0   2   
3     0     0        0   0   0   0    0   0   0   0   ...     1   0   0   0   
4     0     0        0   0   0   0    0   0   0   0   ...     0   0   0   0   

   飞机  马尼拉  高温  高铁  黄色  黄色预警信号  
0   0    0   0   0   0       0  
1   0    0   0   0   0       0  
2   0    0   0   0   0       0  
3   0    0   0   0   0       0  
4   0    0   0   0   0       0  

[5 rows x 221 columns]

In [31]:
n_features = 1000

In [32]:
tf_vectorizer = CountVectorizer(max_features=n_features,
                               max_df=max_df,
                               min_df=min_df,
                               token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                               stop_words=frozenset(stopwords))

In [33]:
term_matrix = pd.DataFrame(tf_vectorizer.fit_transform(X.cutted_text).toarray(), columns=tf_vectorizer.get_feature_names())

In [34]:
term_matrix.head()

baby  doge  r2tuaac  一带  七夕  七天  三亚市  上岸  下沉  不语   ...    预警  风力  风速  风雨  \
0     0     0        0   0   0   0    0   0   0   0   ...     0   0   0   0   
1     0     0        0   0   0   0    0   0   0   0   ...     0   1   0   0   
2     0     0        0   0   0   1    0   1   0   0   ...     0   0   0   2   
3     0     0        0   0   0   0    0   0   0   0   ...     1   0   0   0   
4     0     0        0   0   0   0    0   0   0   0   ...     0   0   0   0   

   飞机  马尼拉  高温  高铁  黄色  黄色预警信号  
0   0    0   0   0   0       0  
1   0    0   0   0   0       0  
2   0    0   0   0   0       0  
3   0    0   0   0   0       0  
4   0    0   0   0   0       0  

[5 rows x 221 columns]

In [35]:
term_matrix.shape

(409, 221)

In [36]:
tf = tf_vectorizer.fit_transform(X.cutted_text)

In [37]:
from sklearn.decomposition import LatentDirichletAllocation

In [38]:
n_topics = 5
lda = LatentDirichletAllocation(n_topics=n_topics,
                               max_iter=50,
                               learning_method='online',
                               learning_offset=50.,
                               random_state=0)

In [39]:
%%time
lda.fit(tf)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


Wall time: 8.47 s


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=50, mean_change_tol=0.001,
             n_components=10, n_jobs=1, n_topics=5, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [40]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print('Topic #%d:' % topic_idx)
        print(' '.join([feature_names[i]
                      for i in topic.argsort()[:-n_top_words -1:-1]]))
    print()

In [41]:
n_top_words = 20

In [42]:
tf_feature_names = tf_vectorizer.get_feature_names()
print_top_words(lda, tf_feature_names, n_top_words)

Topic #0:
热带 台风 低压 南海 天气话你知 海面 消息 热带风暴 预警 北方 菲律宾 东部 白色 加强 我区 二哈 扰动 沿海 海南岛 趋向
Topic #1:
中心 公里 转发 微博 台风 最大 风力 附近 东经 北纬 气压 天鸽 百帕 方向 最低 热带风暴 海面 台风消息 南海 洋面
Topic #2:
台风 帕卡 风雨 简单 天鸽 帕卡影响广州 登陆 苗柏 小编8天气 彩虹 阵风 随手拍广州 暴雨 转发 允悲 预报 出门 上岸 预警 陆地
Topic #3:
深圳 南沙 帕卡影响广州 运营 警惕 苗柏 珠海 一带 茂名 湛江 惠东 阳江 穿过 风雨 洛克 天气话你知 停止 消息 台山 粤西
Topic #4:
台风 登陆 卡努 移动 广东 预警 强度 方向 海南 沿海 我市 热带风暴 帕卡 沿海地区 蓝色 受其 阵风 信号 降水 南沙



In [43]:
import pyLDAvis
import pyLDAvis.sklearn
pyLDAvis.enable_notebook()
pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]


PreparedData(topic_coordinates=            Freq  cluster  topics         x         y
topic                                                
1      56.908594        1       1  0.301637 -0.055821
4      17.458008        1       2 -0.069176 -0.019680
0      16.024237        1       3 -0.008505  0.218845
2       7.476354        1       4 -0.127002 -0.114484
3       2.132807        1       5 -0.096954 -0.028859, topic_info=     Category        Freq    Term       Total  loglift  logprob
term                                                           
68    Default  311.000000      台风  311.000000  30.0000  30.0000
156   Default   79.000000      热带   79.000000  29.0000  29.0000
31    Default   68.000000      低压   68.000000  28.0000  28.0000
93    Default   71.000000      帕卡   71.000000  27.0000  27.0000
20    Default  282.000000      中心  282.000000  26.0000  26.0000
103   Default  172.000000      微博  172.000000  25.0000  25.0000
196   Default  179.000000      转发  179.000000  24.0000  24.0000
214   Default   35.000000      风雨   35.000000  23.0000  23.0000
84    Default   94.000000      天鸽   94.000000  22.0000  22.0000
164   Default   61.000000      登陆   61.000000  21.0000  21.0000
60    Default   45.000000      卡努   45.000000  20.0000  20.0000
170   Default   75.000000      移动   75.000000  19.0000  19.0000
179   Default   31.000000      苗柏   31.000000  18.0000  18.0000
59    Default   70.000000      南海   70.000000  17.0000  17.0000
96    Default   34.000000      广东   34.000000  16.0000  16.0000
58    Default   20.000000      南沙   20.000000  15.0000  15.0000
82    Default   27.000000   天气话你知   27.000000  14.0000  14.0000
94    Default   18.000000  帕卡影响广州   18.000000  13.0000  13.0000
153   Default   15.000000      深圳   15.000000  12.0000  12.0000
211   Default   47.000000      预警   47.000000  11.0000  11.0000
172   Default   17.000000      简单   17.000000  10.0000  10.0000
151   Default   84.000000      海面   84.000000   9.0000   9.0000
152   Default   26.000000      消息   26.000000   8.0000   8.0000
15    Default   82.000000      东经   82.000000   7.0000   7.0000
53    Default   82.000000      北纬   82.000000   6.0000   6.0000
115   Default   90.000000      方向   90.000000   5.0000   5.0000
132   Default   74.000000      气压   74.000000   4.0000   4.0000
44    Default  207.000000      公里  207.000000   3.0000   3.0000
124   Default  113.000000      最大  113.000000   2.0000   2.0000
166   Default   70.000000      百帕   70.000000   1.0000   1.0000
...       ...         ...     ...         ...      ...      ...
94     Topic5    4.422579  帕卡影响广州   18.314258   2.4268  -3.1986
3      Topic5    2.417397      一带   11.178516   2.3164  -3.8026
7      Topic5    1.295748      上岸    6.885926   2.1773  -4.4262
173    Topic5    1.311231      粤西    9.183938   1.9012  -4.4144
143    Topic5    1.360794      洛克   14.114303   1.5086  -4.3773
179    Topic5    2.986881      苗柏   31.131149   1.5038  -3.5911
27     Topic5    0.517344      今晚    5.587358   1.4682  -5.3444
61     Topic5    0.269306      及时    3.616252   1.2504  -5.9972
108    Topic5    0.269508      我国    3.633002   1.2465  -5.9965
136    Topic5    0.268978      沙市    3.634515   1.2441  -5.9985
137    Topic5    0.268780     河源市    3.632590   1.2439  -5.9992
129    Topic5    0.269116     来源于    3.650559   1.2402  -5.9979
54     Topic5    0.269530     北部湾    3.670947   1.2362  -5.9964
28     Topic5    0.269243     从化区    3.772648   1.2078  -5.9975
177    Topic5    0.269557      编号    3.845093   1.1900  -5.9963
112    Topic5    0.269250      提前    3.853769   1.1866  -5.9974
117    Topic5    0.269317      早安    3.857076   1.1860  -5.9972
82     Topic5    1.356856   天气话你知   27.238044   0.8483  -4.3802
152    Topic5    1.323544      消息   26.762591   0.8410  -4.4050
214    Topic5    1.552774      风雨   35.926749   0.7063  -4.2453
34     Topic5    0.272056      信息    3.909163   1.1827  -5.9871
13     Topic5    0.323180     东南方   16.909913  -0.1097  -5.8149
32     Topic5    0.270838      依然    3.949225   1.1680  -5.

In [44]:
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)

In [45]:
%%time
n_topics = 3    #此处的10可以自定义
lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0)
lda.fit(tf)
print_top_words(lda, tf_feature_names, n_top_words)
pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


Topic #0:
台风 热带 低压 中心 公里 海面 南海 移动 预警 加强 风力 热带风暴 北方 方向 最大 菲律宾 强度 附近 我区 消息
Topic #1:
中心 转发 微博 公里 台风 风力 最大 附近 东经 北纬 气压 百帕 天鸽 最低 方向 热带风暴 海面 台风消息 洋面 南海
Topic #2:
台风 登陆 帕卡 风雨 广东 天鸽 沿海 天气话你知 简单 帕卡影响广州 沿海地区 热带风暴 阵风 苗柏 小编8天气 深圳 暴雨 海南 预警 摊手



D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]


Wall time: 17.1 s


In [46]:
%%time
data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
pyLDAvis.show(data)

D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]



Note: if you're in the IPython notebook, pyLDAvis.show() is not the best command
      to use. Consider using pyLDAvis.display(), or pyLDAvis.enable_notebook().
      See more information at http://pyLDAvis.github.io/quickstart.html .

You must interrupt the kernel to end this command

Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]


127.0.0.1 - - [21/Jul/2018 21:43:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Jul/2018 21:43:54] "GET /LDAvis.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jul/2018 21:43:54] "GET /d3.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Jul/2018 21:43:54] "GET /LDAvis.js HTTP/1.1" 200 -



stopping Server...
Wall time: 21min 26s


## 日常预报细分主题的结果打标签

In [47]:
# Doc Topics 结果
# 通过fit_transform函数,可以得到文档主题分布,Doc_Topic distribution matrix
doctopic_matrix = lda.fit_transform(tf) # numpy.ndarray
print(doctopic_matrix)
print(doctopic_matrix.shape)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


[[ 0.11111971  0.77775512  0.11112517]
 [ 0.01407895  0.94480601  0.04111504]
 [ 0.01636432  0.01680319  0.96683249]
 ..., 
 [ 0.11111971  0.77775512  0.11112517]
 [ 0.11111971  0.77775512  0.11112517]
 [ 0.11111971  0.77775512  0.11112517]]
(409, 3)


In [48]:
doctopic = pd.DataFrame(doctopic_matrix, columns=['热带风暴：热带低压消息', 
                                                  '热带风暴：台风中心消息', 
                                                  '热带风暴：台风登陆广东'])
#注意此处的主题排序是根据print_top_words(lda, tf_feature_names, n_top_words)的关键词来确定的，而非ldavis呈现的12345，那里只是按照热度排序。
doctopic.head()

热带风暴：热带低压消息  热带风暴：台风中心消息  热带风暴：台风登陆广东
0     0.111120     0.777755     0.111125
1     0.014079     0.944806     0.041115
2     0.016364     0.016803     0.966832
3     0.682048     0.300442     0.017510
4     0.111120     0.777755     0.111125

In [49]:
doctopic.shape

(409, 3)

In [50]:
global collist
collist = list(doctopic.columns)

def appendmax(sr):
    one = sr.idxmax()
    maxindex = pd.Series(one)
    sr = sr.append(maxindex)
    return sr

dfe = doctopic.apply(lambda x:appendmax(x), axis=1)
dfe.columns = collist + ['所属分类']
# dfe.to_csv('cluster.csv')
dfe.head()

热带风暴：热带低压消息  热带风暴：台风中心消息  热带风暴：台风登陆广东         所属分类
0     0.111120     0.777755     0.111125  热带风暴：台风中心消息
1     0.014079     0.944806     0.041115  热带风暴：台风中心消息
2     0.016364     0.016803     0.966832  热带风暴：台风登陆广东
3     0.682048     0.300442     0.017510  热带风暴：热带低压消息
4     0.111120     0.777755     0.111125  热带风暴：台风中心消息

In [51]:
dfe.shape

(409, 4)

In [52]:
rdfb.drop('所属分类', axis=1, inplace=True)
rdfb.shape

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


(409, 2)

In [53]:
rdfb.to_csv('rdfb.csv', encoding='gb18030')

In [54]:
rdfb = pd.read_csv('rdfb.csv', encoding='gb18030')
rdfb.head()

id   statdate                                               text
0  3586  2017/8/22                                               转发微博
1  3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...
2  3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...
3  3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...
4  3645  2017/8/23                                               转发微博

In [55]:
frames = [rdfb, dfe['所属分类']]
result = pd.concat(frames, axis = 1)
result.head()

id   statdate                                               text  \
0  3586  2017/8/22                                               转发微博   
1  3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...   
2  3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...   
3  3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...   
4  3645  2017/8/23                                               转发微博   

          所属分类  
0  热带风暴：台风中心消息  
1  热带风暴：台风中心消息  
2  热带风暴：台风登陆广东  
3  热带风暴：热带低压消息  
4  热带风暴：台风中心消息

In [56]:
result.to_csv('LDA_clustered_rdfb.csv', encoding='gb18030')

In [57]:
# %%time
# n_topics = 10    #此处的10可以自定义
# lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
#                                 learning_method='online',
#                                 learning_offset=50.,
#                                 random_state=0)
# lda.fit(tf)
# print_top_words(lda, tf_feature_names, n_top_words)
# pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

# %%time
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)