In [1]:
import time
import pandas as pd
import numpy as np
%matplotlib inline

# 一、读入原始文本数据

In [2]:
df = pd.read_csv('data/weibo_text_data.csv', encoding='gb18030')
df.head()

id   statdate                                               text
0  3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...
1  3586  2017/8/22                                               转发微博
2  3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...
3  3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...
4  3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...

In [3]:
df.shape

(7428, 3)

# 二、主题挖掘

In [4]:
df.text.value_counts()

转发微博                                                                                                                                                      139
#随手拍广州#                                                                                                                                                    14
#广州天气预警#                                                                                                                                                   14
#随手拍广州# [憧憬][憧憬][憧憬]                                                                                                                                       10
【拜祭提醒】广州市应急办、民政局提醒您：预计今日特别是14时至16时，我市各主要拜祭场所将出现人流、车流高峰，拜祭场所周边车位紧张、交通拥堵，请尽量选择公共交通工具错峰出行，野外拜祭务必注意用火安全。倡导文明拜祭、无烟拜祭、鲜花缅怀。                                       4
目前广州市花都区无雨，预计未来一小时花都区部分镇街有雨，请留意天气变化。                                                                                                                        4
#随手拍广州# [笑而不语]                                      

In [5]:
X = df.loc[:, ['text']]    #之前写成X = df[['comment']]

In [6]:
X.shape

(7428, 1)

In [7]:
X.head()

text
0  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...
1                                               转发微博
2  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...
3  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...
4  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...

In [8]:
X.dtypes

text    object
dtype: object

In [9]:
X.text.describe()

count     7428
unique    7226
top       转发微博
freq       139
Name: text, dtype: object

In [10]:
X.text.value_counts()

转发微博                                                                                                                                                      139
#随手拍广州#                                                                                                                                                    14
#广州天气预警#                                                                                                                                                   14
#随手拍广州# [憧憬][憧憬][憧憬]                                                                                                                                       10
【拜祭提醒】广州市应急办、民政局提醒您：预计今日特别是14时至16时，我市各主要拜祭场所将出现人流、车流高峰，拜祭场所周边车位紧张、交通拥堵，请尽量选择公共交通工具错峰出行，野外拜祭务必注意用火安全。倡导文明拜祭、无烟拜祭、鲜花缅怀。                                       4
目前广州市花都区无雨，预计未来一小时花都区部分镇街有雨，请留意天气变化。                                                                                                                        4
#随手拍广州# [笑而不语]                                      

In [11]:
import jieba

In [12]:
def chinese_word_cut(mytext):
    return ' '.join(jieba.cut(mytext))

In [13]:
jieba.load_userdict("userdict_weibo.txt")

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\wu\AppData\Local\Temp\jieba.cache
Loading model cost 0.992 seconds.
Prefix dict has been built succesfully.


In [14]:
%%time
X['cutted_text'] = X.text.apply(chinese_word_cut)

Wall time: 3.98 s


In [15]:
X.head()

text  \
0  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...   
1                                               转发微博   
2  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...   
3  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...   
4  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...   

                                         cutted_text  
0  http : / / t . cn / h91BSI 【 升级 气象 灾害 应急 响应 通知...  
1                                              转发 微博  
2  http : / / t . cn / h91BSI 【 台风 紧急警报 】 今天下午 16...  
3  【 七天 天气预报 — “ 天鸽 ” 上岸 ， 仍 有 风雨 】 # 天气话你知 #   #...  
4  http : / / t . cn / h91BSI 【 台风 蓝色 预警 信号 】 今年 ...

In [16]:
X.shape

(7428, 2)

In [17]:
def get_custom_stopwords(stop_words_file):
    with open(stop_words_file, encoding='utf-8') as f:
        stopwords = f.read( )
    stopwords_list = stopwords.split('\n')
    custom_stopwords_list = [i for i in stopwords_list]
    return custom_stopwords_list

In [18]:
stop_words_file = 'mystopwords.txt'
stopwords = get_custom_stopwords(stop_words_file)

In [19]:
stopwords[-10:]

['没错', '缓慢', '增加', '务必', '较强', '辐射', '时段', '雷雨', '', '']

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
vect = CountVectorizer()

In [22]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [23]:
term_matrix.head()

00  01  0125  02  03  04  05  06  062  07 ...  龙岩  龙江  龙洞  龙穴  龙胜  龙舟  龙虾  \
0   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   
1   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   
2   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   
3   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   
4   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   

   龙镇  龟蛇静  龟速  
0   0    0   0  
1   0    0   0  
2   0    0   0  
3   0    0   0  
4   0    0   0  

[5 rows x 12755 columns]

In [24]:
term_matrix.shape

(7428, 12755)

In [25]:
# df.head()

In [26]:
# df.shape

In [27]:
# %%time
# frames = [df['id'], df['statdate'], term_matrix]
# result = pd.concat(frames, axis = 1)

In [28]:
# result.head()

In [29]:
# result.shape

In [30]:
# %%time
# result.to_csv('output.csv', encoding='gb18030')

In [31]:
vect = CountVectorizer(stop_words=frozenset(stopwords)) #加上停用词去除功能

In [32]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [33]:
term_matrix.head()

00  01  0125  02  03  04  05  06  062  07 ...  龙岩  龙江  龙洞  龙穴  龙胜  龙舟  龙虾  \
0   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   
1   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   
2   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   
3   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   
4   0   0     0   0   0   0   0   0    0   0 ...   0   0   0   0   0   0   0   

   龙镇  龟蛇静  龟速  
0   0    0   0  
1   0    0   0  
2   0    0   0  
3   0    0   0  
4   0    0   0  

[5 rows x 11960 columns]

In [34]:
max_df = 0.8 # 在超过这一比例的文档中出现的关键词（过于平凡），去除掉。
min_df = 3 # 在低于这一数量的文档中出现的关键词（过于独特），去除掉。

In [35]:
vect = CountVectorizer(max_df=max_df,
                      min_df=min_df,
                      token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                      stop_words=frozenset(stopwords))

In [36]:
term_matrix = pd.DataFrame(vect.fit_transform(X.cutted_text).toarray(), columns=vect.get_feature_names())

In [37]:
term_matrix.head()

____  _____  ________  app  baby  boss  bsd  call  catcat  christinez ...  \
0     0      0         0    0     0     0    0     0       0           0 ...   
1     0      0         0    0     0     0    0     0       0           0 ...   
2     0      0         0    0     0     0    0     0       0           0 ...   
3     0      0         0    0     0     0    0     0       0           0 ...   
4     0      0         0    0     0     0    0     0       0           0 ...   

   黄阁  黑线  黑色  默默  鼓掌  鼻子  鼻炎  齐飞  龙江  龙穴  
0   0   0   0   0   0   0   0   0   0   0  
1   0   0   0   0   0   0   0   0   0   0  
2   0   0   0   0   0   0   0   0   0   0  
3   0   0   0   0   0   0   0   0   0   0  
4   0   0   0   0   0   0   0   0   0   0  

[5 rows x 2975 columns]

In [38]:
n_features = 1000

In [39]:
tf_vectorizer = CountVectorizer(max_features=n_features,
                               max_df=max_df,
                               min_df=min_df,
                               token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                               stop_words=frozenset(stopwords))

In [40]:
term_matrix = pd.DataFrame(tf_vectorizer.fit_transform(X.cutted_text).toarray(), columns=tf_vectorizer.get_feature_names())

In [41]:
term_matrix.head()

cry  doge  emmm  ing  mm  or  ps  r2tuaac  r2wj72v  r2wjcgp ...  鲜花  鳌头  \
0    0     0     0    0   0   0   0        0        0        0 ...   0   0   
1    0     0     0    0   0   0   0        0        0        0 ...   0   0   
2    0     0     0    0   0   0   0        0        0        0 ...   0   0   
3    0     0     0    0   0   0   0        0        0        0 ...   0   0   
4    0     0     0    0   0   0   0        0        0        0 ...   0   0   

   鸡腿  黄人  黄埔区  黄绿色  黄色  黄色预警信号  黄阁  鼓掌  
0   0   0    0    0   0       0   0   0  
1   0   0    0    0   0       0   0   0  
2   0   0    0    0   0       0   0   0  
3   0   0    0    0   0       0   0   0  
4   0   0    0    0   0       0   0   0  

[5 rows x 1000 columns]

In [42]:
term_matrix.shape

(7428, 1000)

In [43]:
df.shape

(7428, 3)

In [44]:
%%time
frames = [df['id'], df['statdate'], term_matrix]
result_handled = pd.concat(frames, axis = 1)

Wall time: 128 ms


In [45]:
result_handled.shape

(7428, 1002)

In [46]:
result_handled.head()

id   statdate  cry  doge  emmm  ing  mm  or  ps  r2tuaac ...  鲜花  鳌头  鸡腿  \
0  3585  2017/8/22    0     0     0    0   0   0   0        0 ...   0   0   0   
1  3586  2017/8/22    0     0     0    0   0   0   0        0 ...   0   0   0   
2  3641  2017/8/23    0     0     0    0   0   0   0        0 ...   0   0   0   
3  3642  2017/8/23    0     0     0    0   0   0   0        0 ...   0   0   0   
4  3643  2017/8/23    0     0     0    0   0   0   0        0 ...   0   0   0   

   黄人  黄埔区  黄绿色  黄色  黄色预警信号  黄阁  鼓掌  
0   0    0    0   0       0   0   0  
1   0    0    0   0       0   0   0  
2   0    0    0   0       0   0   0  
3   0    0    0   0       0   0   0  
4   0    0    0   0       0   0   0  

[5 rows x 1002 columns]

In [47]:
# %%time
# result_handled.to_csv('output_handled.csv', encoding='gb18030')

In [48]:
tf = tf_vectorizer.fit_transform(X.cutted_text)

In [49]:
from sklearn.decomposition import LatentDirichletAllocation

In [50]:
n_topics = 5
lda = LatentDirichletAllocation(n_topics=n_topics,
                               max_iter=50,
                               learning_method='online',
                               learning_offset=50.,
                               random_state=0)

In [51]:
%%time
lda.fit(tf)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


Wall time: 52.6 s


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=50, mean_change_tol=0.001,
             n_components=10, n_jobs=1, n_topics=5, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [52]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print('Topic #%d:' % topic_idx)
        print(' '.join([feature_names[i]
                      for i in topic.argsort()[:-n_top_words -1:-1]]))
    print()

In [53]:
n_top_words = 20

In [54]:
tf_feature_names = tf_vectorizer.get_feature_names()
print_top_words(lda, tf_feature_names, n_top_words)

Topic #0:
广州市 气象台 多云 各区 轻微 天气话你知 预测 阴天 广州市区 高峰期 晴到多云 夜间 我市 偏北风 和缓 相对湿度 广州市今日天气 阵雨 雷阵雨 监测
Topic #1:
预警 气象台 我区 暴雨 解除 信号 r2tuaac 黄色预警信号 雷雨大风 南沙 黄色 生效 花都区 雷雨云 阵风 城区 黄埔区 高温 森林 毫米
Topic #2:
小编8天气 天气话你知 随手拍广州 不语 小编 doge 二哈 简单 摊手 允悲 憧憬 天气预报 冷空气 早安 小伙伴 七天 阳光 晚安 降水 出门
Topic #3:
气象 应急 灾害 广州市 响应 大雾 指挥部 启动 暴雨 解除 留意 通知 防御 气象台 监测 办公室 文章 规定 信息 黄人
Topic #4:
台风 中心 公里 微博 转发 移动 风力 方向 最大 附近 天鸽 热带风暴 帕卡 海面 南海 热带 北纬 东经 强度 最低



In [ ]:
import pyLDAvis
import pyLDAvis.sklearn
pyLDAvis.enable_notebook()
pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]


PreparedData(topic_coordinates=            Freq  cluster  topics         x         y
topic                                                
2      33.868999        1       1  0.020999 -0.377437
1      26.287876        1       2 -0.073309  0.132143
0      23.768283        1       3 -0.237103  0.122818
4       8.614230        1       4  0.376457  0.123828
3       7.460612        1       5 -0.087044 -0.001352, topic_info=     Category         Freq     Term        Total  loglift  logprob
term                                                              
419   Default  3265.000000      广州市  3265.000000  30.0000  30.0000
968   Default  1817.000000       预警  1817.000000  29.0000  29.0000
598   Default  3042.000000      气象台  3042.000000  28.0000  28.0000
251   Default   692.000000       台风   692.000000  27.0000  27.0000
316   Default   959.000000       多云   959.000000  26.0000  26.0000
381   Default  1251.000000    小编8天气  1251.000000  25.0000  25.0000
597   Default   511.000000       气象   511.000000  24.0000  24.0000
256   Default   928.000000       各区   928.000000  23.0000  23.0000
865   Default   875.000000       轻微   875.000000  22.0000  22.0000
465   Default   800.000000       我区   800.000000  21.0000  21.0000
77    Default   524.000000       中心   524.000000  20.0000  20.0000
426   Default   392.000000       应急   392.000000  19.0000  19.0000
967   Default   709.000000       预测   709.000000  18.0000  18.0000
555   Default   871.000000       暴雨   871.000000  17.0000  17.0000
137   Default   712.000000       信号   712.000000  16.0000  16.0000
666   Default   351.000000       灾害   351.000000  15.0000  15.0000
829   Default   811.000000       解除   811.000000  14.0000  14.0000
337   Default  1652.000000    天气话你知  1652.000000  13.0000  13.0000
926   Default   602.000000       阴天   602.000000  12.0000  12.0000
942   Default   770.000000    随手拍广州   770.000000  11.0000  11.0000
55    Default   717.000000       不语   717.000000  10.0000  10.0000
7     Default   558.000000  r2tuaac   558.000000   9.0000   9.0000
997   Default   544.000000   黄色预警信号   544.000000   8.0000   8.0000
380   Default   673.000000       小编   673.000000   7.0000   7.0000
960   Default   503.000000     雷雨大风   503.000000   6.0000   6.0000
168   Default   263.000000       公里   263.000000   5.0000   5.0000
1     Default   577.000000     doge   577.000000   4.0000   4.0000
984   Default   422.000000      高峰期   422.000000   3.0000   3.0000
542   Default   413.000000     晴到多云   413.000000   2.0000   2.0000
274   Default   224.000000       响应   224.000000   1.0000   1.0000
...       ...          ...      ...          ...      ...      ...
826    Topic5    61.189827       规定    62.015178   2.5821  -4.5799
138    Topic5    60.410088       信息    61.238576   2.5819  -4.5927
993    Topic5    60.044380       黄人    60.869707   2.5819  -4.5988
489    Topic5    59.232532       拜祭    60.054478   2.5818  -4.6124
495    Topic5    58.499718       据市    59.321617   2.5816  -4.6249
741    Topic5    56.698459     空气质量    57.528249   2.5810  -4.6562
983    Topic5    55.838221       高兴    56.663719   2.5809  -4.6714
812    Topic5    51.573358       街道    52.396850   2.5797  -4.7509
345    Topic5    50.231810       头条    51.057438   2.5792  -4.7773
584    Topic5    48.115000     横渡珠江    48.939512   2.5785  -4.8203
966    Topic5    40.787715       预案    41.609629   2.5756  -4.9855
688    Topic5    38.276319       现场    39.100646   2.5742  -5.0491
302    Topic5    37.909402       场所    38.731776   2.5741  -5.0587
531    Topic5    36.990851       春运    37.817803   2.5734  -5.0832
427    Topic5    36.587059     延迟上学    37.411953   2.5732  -5.0942
599    Topic5    36.023302      气象局    36.851411   2.5728  -5.1097
358    Topic5    33.999909       学生    34.824453   2.5716  -5.1675
496    Topic5    33.306955       措施    34.135904   2.5709  -5.1881
20     Topic5    32.875643       一条    33.708532   2.5705  -5.2012
390    Topic5    32.116765       山区    32.949000   2.5699  -5.2245
697    Topic5    77.709563  

In [ ]:
data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
pyLDAvis.show(data)

D:\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  topic_term_dists = topic_term_dists.ix[topic_order]



Note: if you're in the IPython notebook, pyLDAvis.show() is not the best command
      to use. Consider using pyLDAvis.display(), or pyLDAvis.enable_notebook().
      See more information at http://pyLDAvis.github.io/quickstart.html .

You must interrupt the kernel to end this command

Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]


127.0.0.1 - - [24/Jul/2018 11:02:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Jul/2018 11:02:43] "GET /LDAvis.css HTTP/1.1" 200 -
127.0.0.1 - - [24/Jul/2018 11:02:43] "GET /d3.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Jul/2018 11:02:43] "GET /LDAvis.js HTTP/1.1" 200 -


In [ ]:
# %%time
# n_topics = 6    #此处的10可以自定义
# lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
#                                 learning_method='online',
#                                 learning_offset=50.,
#                                 random_state=0)
# lda.fit(tf)
# print_top_words(lda, tf_feature_names, n_top_words)
# pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

In [ ]:
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)

# 三、根据主题词分布计算信息熵

In [268]:
# 结果展示
# Topic Words 结果
topicword_matrix = lda.components_ # numpy.ndarray
print(topicword_matrix[0,1]) # topicword_matrix[i,j]: word j was assigned to topic i
print(topicword_matrix.shape)
# topicword_matrix / topicword_matrix.sum(axis=1)[:, np.newaxis] # normalization
# topicword_matrix / topicword_matrix.sum(axis=0)[:, np.newaxis] # normalization
topicword_matrix

0.200085468525
(5, 1000)


array([[  2.00067125e-01,   2.00085469e-01,   2.00369203e-01, ...,
          2.00192570e-01,   2.00001288e-01,   2.00053162e-01],
       [  2.00586975e-01,   2.00266222e-01,   2.00047781e-01, ...,
          5.27553492e+02,   9.66658831e+00,   2.00191576e-01],
       [  1.67464777e+02,   6.30318266e+02,   1.12978609e+01, ...,
          2.00187015e-01,   2.00000824e-01,   6.07532455e+01],
       [  2.01344077e-01,   2.02376137e-01,   2.00203511e-01, ...,
          2.02018481e-01,   2.00004770e-01,   2.06645060e-01],
       [  2.00929311e-01,   2.01054758e-01,   2.00023409e-01, ...,
          2.02208108e-01,   2.00308843e-01,   2.00771524e-01]])

In [269]:
topicword_matrix / topicword_matrix.sum(axis=0)[np.newaxis, :] # normalization

array([[  1.18898113e-03,   3.17031340e-04,   1.65614847e-02, ...,
          3.78895622e-04,   1.91079699e-02,   3.24967861e-03],
       [  1.19207055e-03,   3.17317739e-04,   1.65349177e-02, ...,
          9.98477157e-01,   9.23538448e-01,   3.25192702e-03],
       [  9.95228273e-01,   9.98726423e-01,   9.33822905e-01, ...,
          3.78885109e-04,   1.91079256e-02,   9.86880289e-01],
       [  1.19656994e-03,   3.20660858e-04,   1.65477895e-02, ...,
          3.82351443e-04,   1.91083026e-02,   3.35675789e-03],
       [  1.19410502e-03,   3.18567160e-04,   1.65329032e-02, ...,
          3.82710341e-04,   1.91373536e-02,   3.26134774e-03]])

In [270]:
topicword = pd.DataFrame(topicword_matrix / topicword_matrix.sum(axis=0)[np.newaxis, :])
topicword

0         1         2         3         4         5         6    \
0  0.001189  0.000317  0.016561  0.017238  0.013276  0.015777  0.004229   
1  0.001192  0.000317  0.016535  0.017331  0.946694  0.015811  0.004236   
2  0.995228  0.998726  0.933823  0.017653  0.013303  0.936695  0.982791   
3  0.001197  0.000321  0.016548  0.930468  0.013442  0.015774  0.004339   
4  0.001194  0.000319  0.016533  0.017310  0.013284  0.015941  0.004404   

        7         8         9      ...          990       991       992  \
0  0.000369  0.017519  0.001550    ...     0.012329  0.006880  0.001823   
1  0.998518  0.017529  0.001526    ...     0.012329  0.972473  0.001822   
2  0.000369  0.929866  0.993861    ...     0.012466  0.006873  0.992704   
3  0.000371  0.017566  0.001536    ...     0.950529  0.006898  0.001822   
4  0.000372  0.017520  0.001527    ...     0.012347  0.006875  0.001829   

        993       994       995       996       997       998       999  
0  0.003835  0.000624  0.018925  0.000488  0.000379  0.019108  0.003250  
1  0.003835  0.997512  0.018977  0.998044  0.998477  0.923538  0.003252  
2  0.003877  0.000620  0.651771  0.000489  0.000379  0.019108  0.986880  
3  0.984599  0.000623  0.291350  0.000490  0.000382  0.019108  0.003357  
4  0.003855  0.000622  0.018978  0.000489  0.000383  0.019137  0.003261  

[5 rows x 1000 columns]

In [271]:
np.log2(topicword)

0          1         2         3         4         5         6    \
0 -9.716058 -11.623087 -5.916024 -5.858268 -6.234984 -5.985991 -7.885519   
1 -9.712315 -11.621784 -5.918340 -5.850517 -0.079030 -5.982904 -7.882959   
2 -0.006901  -0.001839 -0.098779 -5.823921 -6.232101 -0.094348 -0.025043   
3 -9.706880 -11.606664 -5.917218 -0.103971 -6.217100 -5.986263 -7.848373   
4 -9.709855 -11.616115 -5.918516 -5.852266 -6.234115 -5.971088 -7.826892   

         7         8         9      ...          990       991       992  \
0 -11.404415 -5.834953 -9.333488    ...    -6.341785 -7.183307 -9.099858   
1  -0.002139 -5.834080 -9.355821    ...    -6.341774 -0.040270 -9.099992   
2 -11.404489 -0.104905 -0.008884    ...    -6.325865 -7.184787 -0.010565   
3 -11.394899 -5.831097 -9.346516    ...    -0.073198 -7.179677 -9.099870   
4 -11.390578 -5.834850 -9.355504    ...    -6.339684 -7.184321 -9.094773   

        993        994       995        996        997       998       999  
0 -8.026616 -10.647265 -5.723587 -11.000862 -11.365912 -5.709682 -8.265487  
1 -8.026738  -0.003594 -5.719603  -0.002825  -0.002199 -0.114756 -8.264489  
2 -8.010780 -10.655410 -0.617564 -10.998842 -11.365952 -5.709685 -0.019053  
3 -0.022392 -10.649110 -1.779175 -10.995151 -11.352813 -5.709657 -8.218716  
4 -8.019177 -10.651769 -5.719545 -10.996521 -11.351459 -5.707465 -8.260316  

[5 rows x 1000 columns]

In [272]:
pd.Series(-(topicword * np.log2(topicword)).sum()).head()

0    0.053207
1    0.016631
2    0.483847
3    0.503234
4    0.406889
dtype: float64

In [273]:
pd.Series(tf_feature_names).head()

0     cry
1    doge
2    emmm
3     ing
4      mm
dtype: object

In [274]:
frames = [pd.Series(tf_feature_names), pd.Series(-(topicword * np.log2(topicword)).sum())]

In [275]:
etp = pd.concat(frames, axis=1)
etp.rename(columns={0:'word', 1:'entropy'}, inplace=True)
etp.head()

word   entropy
0   cry  0.053207
1  doge  0.016631
2  emmm  0.483847
3   ing  0.503234
4    mm  0.406889

In [276]:
etp.shape

(1000, 2)

In [277]:
etp.sort_values('entropy', ascending=False, inplace=True)
etp.head()

word   entropy
873   过程  1.846107
825   观测  1.728582
821   西南  1.629587
102   人员  1.592662
18    一带  1.580564

In [246]:
etp.to_csv('etp0721.csv', encoding='gb18030')

## 根据主题挖掘的结果打标签

In [253]:
# Doc Topics 结果
# 通过fit_transform函数,可以得到文档主题分布,Doc_Topic distribution matrix
doctopic_matrix = lda.fit_transform(tf) # numpy.ndarray
print(doctopic_matrix)
print(doctopic_matrix.shape)

D:\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


[[ 0.00599226  0.00592337  0.00588235  0.97611153  0.00609049]
 [ 0.06666668  0.06666668  0.06666668  0.06666673  0.73333323]
 [ 0.00833334  0.0083418   0.00833618  0.00833641  0.96665227]
 ..., 
 [ 0.0666667   0.0666667   0.73333301  0.0666668   0.06666678]
 [ 0.02857149  0.02857148  0.88571376  0.02857165  0.02857162]
 [ 0.02500004  0.02503119  0.77495728  0.02500016  0.15001132]]
(7428, 5)


In [254]:
doctopic = pd.DataFrame(doctopic_matrix, columns=['日常天气预报', 
                                                  '预警信号',  
                                                  '粉丝互动', 
                                                  '气象灾害应急响应',
                                                  '热带风暴'])
#注意此处的主题排序是根据print_top_words(lda, tf_feature_names, n_top_words)的关键词来确定的，而非ldavis呈现的12345，那里只是按照热度排序。
doctopic.head()


日常天气预报      预警信号      粉丝互动  气象灾害应急响应      热带风暴
0  0.005992  0.005923  0.005882  0.976112  0.006090
1  0.066667  0.066667  0.066667  0.066667  0.733333
2  0.008333  0.008342  0.008336  0.008336  0.966652
3  0.010734  0.063784  0.219859  0.010898  0.694726
4  0.009814  0.216013  0.009524  0.009534  0.755115

In [255]:
global collist
collist = list(doctopic.columns)

def appendmax(sr):
    one = sr.idxmax()
    maxindex = pd.Series(one)
    sr = sr.append(maxindex)
    return sr

dfe = doctopic.apply(lambda x:appendmax(x), axis=1)
dfe.columns = collist + ['所属分类']
# dfe.to_csv('cluster.csv')
dfe.head()

日常天气预报      预警信号      粉丝互动  气象灾害应急响应      热带风暴      所属分类
0  0.005992  0.005923  0.005882  0.976112  0.006090  气象灾害应急响应
1  0.066667  0.066667  0.066667  0.066667  0.733333      热带风暴
2  0.008333  0.008342  0.008336  0.008336  0.966652      热带风暴
3  0.010734  0.063784  0.219859  0.010898  0.694726      热带风暴
4  0.009814  0.216013  0.009524  0.009534  0.755115      热带风暴

In [256]:
df.head()

id   statdate                                               text
0  3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...
1  3586  2017/8/22                                               转发微博
2  3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...
3  3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...
4  3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...

In [257]:
frames = [df, dfe['所属分类']]
result = pd.concat(frames, axis = 1)
result.head()

id   statdate                                               text  \
0  3585  2017/8/22  http://t.cn/h91BSI【升级气象灾害应急响应通知】据市气象台监测，广州市达到启...   
1  3586  2017/8/22                                               转发微博   
2  3641  2017/8/23  http://t.cn/h91BSI【台风紧急警报】今天下午16时，今年第13号台风“天鸽”...   
3  3642  2017/8/23  【七天天气预报—“天鸽”上岸，仍有风雨】#天气话你知# #13号台风天鸽# 强台风“天鸽”已...   
4  3643  2017/8/23  http://t.cn/h91BSI【台风蓝色预警信号】今年第13号台风“天鸽”，23日17...   

       所属分类  
0  气象灾害应急响应  
1      热带风暴  
2      热带风暴  
3      热带风暴  
4      热带风暴

In [259]:
result.to_csv('LDA_clustered_5.csv', encoding='gb18030')

In [204]:
# %%time
# n_topics = 10    #此处的10可以自定义
# lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=50,
#                                 learning_method='online',
#                                 learning_offset=50.,
#                                 random_state=0)
# lda.fit(tf)
# print_top_words(lda, tf_feature_names, n_top_words)
# pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)

In [205]:
# %%time
# data = pyLDAvis.sklearn.prepare(lda, tf, tf_vectorizer)
# pyLDAvis.show(data)